Use Normalized data in ExperimentDetails
Automattic/abacus pull request #265
Opened 2020-08-20 04:13 UTC by jessie-ross

**This PR adds normalized data usage in ExperimentDetails:**
- Adds `normalizr` schemas for experiment
- Adds `normalizeExperiment` function
- Removes `Experiments.getDeployedVariation` as it is no longer necessary
   - Add data test for `deployedVariationId` - this will check on outgoing data as well as incoming. 
- Removes `resolveMetricAssignments` in MetricsPanel
- Removes `resolveSegmentAssignments` from SegmentsPanel

Looks like a lot but isn't too much:
- 7 of the files are test files where we just change them to use normalized data.
- Other than the above removal we are just adding and threading the normalized data through.

This is part 2/3 of #236 and should be done before we do further work in ExperimentDetails for the CRUD.
- A departure is that I am using `normalizedXEntities` instead of `normalizedXData` as it makes things simpler.

See also part 1/3 at #240.

## How has this been tested?

- Automated tests that cover added/changed functionality
- Manual testing with mock data (locally)

2020-08-20 05:42 UTC, yanirs requested changes
See inline comments: The main issues I see are similar comments to those addressed on #240 and `normalizeExperiment()` being too unintuitive and a leaky abstraction of the `normlizr` library. I haven't looked through all the files yet since my main comments would affect everything else.

2020-08-20 05:42 UTC, yanirs commented on lib/normalizers.test.ts
> +      // @ts-ignore; This is just for minimal testing
Can you please create a more meaningful test with an actual experiment? This also came up in https://github.com/Automattic/abacus/pull/240#issuecomment-666273443.

2020-08-20 05:42 UTC, yanirs commented on lib/schemas.ts
> +export const metricAssignmentNormalizrSchema = new normalizr.schema.Entity<MetricAssignment>(
Why are these schemas here? I thought we agreed to keep them in `normalizers.ts` and not export them as in #240.

2020-08-20 05:42 UTC, yanirs commented on lib/schemas.ts
> +        : true
I think this would be a bit clearer as
```suggestion
      return _.isNull(experiment.deployedVariation) ||
        experiment.variations.some((variation: Variation) => variation.variationId === experiment.deployedVariationId)
```

2020-08-20 05:42 UTC, yanirs commented on lib/schemas.ts
> +  experiments: Record<number, ExperimentFullNormalized>
Why do we return this and why is it plural? It doesn't seem to be used.

2020-08-20 05:42 UTC, yanirs commented on lib/normalizers.ts
> +export function normalizeExperiment(
This function returns a value that's too hard to use in my opinion. Why not define `ExperimentFullNormalized` to include the raw assignment arrays _and_ the indexed arrays? 

Taking `metricAssignments` as an example, it's very unintuitive that it's an array of `MetricAssignment`s in `ExperimentFull`, an array of numbers in `ExperimentFullNormalized`, and a mapping from ID to `MetricAssignment` in `ExperimentFullNormalizedEntities`. I think we should stick to keeping it as an array of `MetricAssignment`s in `ExperimentFullNormalized` and add an `indexedMetricAssignments` field for the mapping from ID to `MetricAssignment`. 

The same goes for `segmentAssignments` and `variations`. If we include the indexed versions in `ExperimentFullNormalized` we would have a single value that'd be much easier to use.

2020-08-20 05:42 UTC, yanirs commented on lib/schemas.ts
> +    /* istanbul ignore next; this is a data validation test itself */
It's not a test, though. I think it should still be covered.

2020-08-20 05:42 UTC, yanirs commented on components/AudiencePanel.test.tsx
> +  const segments: Segment[] = []
Can we avoid this temporary variable?

2020-08-20 06:07 UTC, jessie-ross commented on lib/schemas.ts
> +export const metricAssignmentNormalizrSchema = new normalizr.schema.Entity<MetricAssignment>(
Ah yep, I forgot about that.

2020-11-13 17:37 UTC, jessie-ross commented
I am still thinking about this, I am now not so convinced of the urgency for it and the method of execution...

2020-11-16 22:12 UTC, yanirs commented
> I am still thinking about this, I am now not so convinced of the urgency for it and the method of execution...

@jessie-ross I'll close this for now as it's very stale. We can always revisit in the future. :slightly_smiling_face:

2020-11-16 22:12 UTC, closed without merging