Add experiment add metric modal
Automattic/abacus pull request #273
Opened 2020-08-21 20:24 UTC by jessie-ross

**This PR adds a modal for Assigning Metrics.**

<img width="723" alt="Screen Shot 2020-08-22 at 4 23 04 am" src="https://user-images.githubusercontent.com/971886/90931391-2e52de00-e42f-11ea-89d2-244b71c612f9.png">

Exactly the same deal as #271 

## How has this been tested?

- Automated tests that cover added/changed functionality
- Manual testing with mock data (locally or on Vercel)
- E2E tests at the end.

2020-08-24 15:28 UTC, withinboredom requested changes
I think we should go ahead and implement the list of metrics in this PR or put this behind some kind of feature flag. As more and more people come to check out Abacus, we probably need for the app to not appear "broken."

![image](https://user-images.githubusercontent.com/1883296/91064139-2eb9c780-e62f-11ea-8aae-c47d470fc7cf.png)

2020-08-24 15:28 UTC, withinboredom commented on components/MetricAssignmentsPanel.tsx
> +              <DialogContent></DialogContent>
Is a list of metrics supposed to go here?

2020-08-25 02:58 UTC, jessie-ross commented on components/MetricAssignmentsPanel.tsx
> +              <DialogContent></DialogContent>
Yep, I decided to stop where I was here as I had made about 5 PRs and didn't want to get too ahead of myself.
This feature should be done within the next day or so.

2020-08-25 03:08 UTC, jessie-ross commented
> I think we should go ahead and implement the list of metrics in this PR or put this behind some kind of feature flag. As more and more people come to check out Abacus, we probably need for the app to not appear "broken."

I was under the assumption that our App wasn't released yet - I would be developing pretty differently if it was.

This is a bit frustrating combining it with the split PRs - we would need to use feature flags a lot as none of the modals are working yet. I was hoping to get some efficiency gains out of doing the modals like this.

In general for a high stability app I suggest moving away from CI to versioned releases.

2020-08-25 07:44 UTC, yanirs commented
> I was under the assumption that our App wasn't released yet - I would be developing pretty differently if it was.

I think we can assume that from the end of the current milestone it'd be in active use, as this is what we're aiming for (full functionality that's needed to manage and run experiments).

> This is a bit frustrating combining it with the split PRs - we would need to use feature flags a lot as none of the modals are working yet. I was hoping to get some efficiency gains out of doing the modals like this.

In my opinion, it's fine to have the "broken" modals for now, as they'll be going away in the next week or two. Alternatively, you could also stack PRs from a root PR and then have a final big merge, or use a feature flag as you suggested.

> In general for a high stability app I suggest moving away from CI to versioned releases.

I'm not fussed either way. Can you please P2 this point? We will need to start caring more about stability very soon.

2020-08-25 08:57 UTC, withinboredom approved these changes
Thanks for comments @yanirs and @jessie-ross, let's merge this!

2020-08-25 09:55 UTC, jessie-ross commented
> Can you please P2 this point? We will need to start caring more about stability very soon.

I mentioned quite a few different approaches (including non-CI) to stability/correctness here: https://betterexperiments.wordpress.com/2020/07/06/thoughts-on-front-end-code-testing/

It might be good to discuss some of those points there.

2020-08-25 15:20 UTC, merged