Add GeneralPanel Edit submit
Automattic/abacus pull request #290
Opened 2020-09-01 07:50 UTC by jessie-ross

**This PR adds submission to the GeneralPanel Edit Modal:**
- Adds `ExperimentsApi.patch`
- Uses `ExperimentsApi.patch` for the submit.
- Beefs up the Save button in the modal.

Currently fails integration tests and local as swagger is failing, it seems to be requiring the `name` property to be present?

Next and Final PR is calling the refresh on the experiment data.

## How has this been tested?

- Automated tests that cover added/changed functionality
- Manual testing with production data (locally)

2020-09-01 08:10 UTC, yanirs commented on api/ExperimentsApi.ts
> +  if (blacklistedKeys.some((key) => keys.includes(key))) {
Do we need this to be a runtime check? Can't we define `experimentPatch` to be of type `Partial<Omit<ExperimentFull, 'experimentId'  | 'exposureEvents' | ...>>`?

2020-09-01 09:10 UTC, jessie-ross commented on api/ExperimentsApi.ts
> +  if (blacklistedKeys.some((key) => keys.includes(key))) {
Well runtime has some advantages over compile-time, generally these functions (`patch` and `create`) don't actually get well typed inputs as we are receiving from user data. I would argue in this case it is preferable to do this runtime.

Although it is arguable whether this is useful at all...

2020-09-01 16:44 UTC, jessie-ross commented
Ok, finally got to the failing integration tests:

> Currently fails integration tests and local as swagger is failing, it seems to be requiring the name property to be present?

@yanirs it might be worth you experimenting with swagger as you have it set up.

2020-09-01 21:53 UTC, yanirs commented
> Ok, finally got to the failing integration tests:
> 
> > Currently fails integration tests and local as swagger is failing, it seems to be requiring the name property to be present?
> 
> @yanirs it might be worth you experimenting with swagger as you have it set up.

It was because I didn't specify 200 as a possible response in the mock. :man_facepalming:
Fixed on SwaggerHub and I'll push a PR to update the doc.

2020-09-01 22:33 UTC, yanirs requested changes
Let's make the panel test verify that Save and Cancel do different things. :slightly_smiling_face: 

Also, I did a quick check [on Vercel](https://abacus-git-add-general-experiments-submit.a8c.vercel.app/experiments/2) and we shouldn't be validating disabled fields:

![Peek 2020-09-02 08-22](https://user-images.githubusercontent.com/3952615/91912515-a73b1b00-ecf6-11ea-8ebc-8240ff7bdb0f.gif)

2020-09-01 22:33 UTC, yanirs commented on __tests__/api/ExperimentsApi.test.ts
> +        ExperimentsApi.patch(0, (rawNewExperiment as unknown) as Partial<ExperimentFull>),
Let's use a realistic experiment ID (> 0).

2020-09-01 22:33 UTC, yanirs commented on api/ExperimentsApi.ts
> +  if (blacklistedKeys.some((key) => keys.includes(key))) {
> Well runtime has some advantages over compile-time, generally these functions (`patch` and `create`) don't actually get well typed inputs as we are receiving from user data. I would argue in this case it is preferable to do this runtime.

Looking at how it's called (with the output of `_.pick()`), there is some type checking going on. Also, an advantage of using the `Partial<Omit<...>>` approach is that the allowed fields are explicitly declared in the function signature. 

> Although it is arguable whether this is useful at all...

Yeah, maybe drop it completely? The backend will reject any fields that can't be updated anyway, and the list of blacklisted keys isn't exhaustive. If we do end up supporting additional fields on the backend, it'll be less work here. :slightly_smiling_face:

2020-09-01 22:33 UTC, yanirs commented on components/GeneralPanel.test.tsx
> +
This is unnecessary as this test doesn't submit the form.

```suggestion
```

2020-09-01 22:33 UTC, yanirs commented on components/GeneralPanel.test.tsx
> +  global.fetch = jest.fn().mockImplementationOnce(async () => ({
As this is a unit test, it'd be better to mock `ExperimentsApi.patch()` and verify that it's called with the expected fields on save. Otherwise, this test isn't really testing much (the behaviour of `Save` is identical to that of `Cancel`).

2020-09-02 01:54 UTC, yanirs commented on components/GeneralPanel.tsx
> +  const onSubmitEdit = async (formData: { experiment: unknown }) => {
I think we can use `{ experiment: typeof generalEditInitialExperiment }` here.

2020-09-02 02:22 UTC, yanirs commented on components/GeneralPanel.tsx
> +    submitContainer: {
Shall we move some of these styles to a higher level? We're losing out on CSS benefits by localising this stuff.

2020-09-02 04:42 UTC, jessie-ross commented on components/GeneralPanel.tsx
> +    submitContainer: {
It might be worth extracting this into a `ProgressButtonContainer` component

2020-09-02 07:21 UTC, jessie-ross commented on components/GeneralPanel.test.tsx
> +  global.fetch = jest.fn().mockImplementationOnce(async () => ({
Mocking `ExperimentsApi.patch()` was a good idea!

2020-09-02 07:22 UTC, jessie-ross commented on components/GeneralPanel.test.tsx
> +
It happens to be needed now as we have slightly different submit logic for disabled experiments.

2020-09-02 08:03 UTC, jessie-ross commented
Ok, I've fixed the issues you have mentioned, these in particular:
- Made sure `endDatetime` isn't validated when it isn't editable.
- Extracted out `LoadingButtonContainer`

2020-09-02 08:46 UTC, yanirs approved these changes
I think we can improve the testing a bit, but nothing for this PR, so let's :ship:

2020-09-02 08:46 UTC, merged