Add validation to MetricAssignment Assign Modal
Automattic/abacus pull request #295
Opened 2020-09-02 16:45 UTC by jessie-ross

**This PR adds validation to the modal, much the same as #288.** 
Video: https://d.pr/v/a5S0Wq

## How has this been tested?

- Automated tests that cover added/changed functionality
- Manual testing with production data (locally)

2020-09-02 23:57 UTC, aaronyan requested changes
Looking good so far! A couple of requests for changes:

- After selecting a metric, the `attribution window` goes red. Can we only make the `attribution window` go red after the user interacts with that form?
- The `minimum difference` form accepts negative numbers. Let's only accept positive numbers.
- The `minimum difference` hint is currently "-". Can we adjust that to be `1.30` or some other placeholder value?
- I wasn't able to test a metric that is type conversions. Does the `minimum difference` field change to % instead of $?

2020-09-04 03:16 UTC, yanirs commented
@jessie-ross it now expects the min difference to be an integer:

![Peek 2020-09-04 13-14](https://user-images.githubusercontent.com/3952615/92195562-ae0d8d80-eeb0-11ea-90bc-89ec148e14d0.gif)

2020-09-04 05:25 UTC, jessie-ross commented
> it now expects the min difference to be an integer:

Ah! This should be fixed now.

2020-09-04 05:41 UTC, yanirs approved these changes

2020-09-04 06:10 UTC, merged