Add button state based on experiment status
Automattic/abacus pull request #309
Opened 2020-09-07 15:56 UTC by jessie-ross

**This PR adds disable state and tooltips to experiment CRUD buttons.**
- Tooltips can probably be improved
- Note sure if I got all the states correct particularly assign metric and conclude.
- For each status we test each button at the same time so we can clearly see what is enabled and what isn't.

## How has this been tested?
- Automated tests that cover added functionality
- Manual testing with production data (locally)
- Manual testing with mock data (locally)

2020-09-07 22:51 UTC, yanirs requested changes
Good progress. Should be good to go with the inline comments, which are all pretty straightforward.

2020-09-07 22:51 UTC, yanirs commented on components/ExperimentPageView.tsx
>  // istanbul ignore file; Even though it sits with components this is a "page" component
Should we remove this now that it's tested?

2020-09-07 22:51 UTC, yanirs commented on components/ExperimentPageView.tsx
> +            <Tooltip title={canEditInWizard ? '' : 'Only available while staging.'}>
`Only available for staging experiments` sounds a bit better to me.

2020-09-07 22:51 UTC, yanirs commented on components/ExperimentPageView.tsx
> +  }
`This experiment has ran` is also possibly true for disabled experiments. :slightly_smiling_face: 

It'd be simpler to change this to `This experiment is <status>`, which makes the mapping unnecessary.

2020-09-07 22:51 UTC, yanirs commented on components/ExperimentPageView.tsx
> +            <Tooltip title={!canRunExperiment ? cantRunExperimentReason[experiment?.status as string] : ''}>
Please reverse the order of the ternary to avoid the double negative and make it consistent with the edit button. Can also inline the reason and turn this into:
```
canRunExperiment ? '' : `This experiment is ${experiment?.status as string}.`
```

By the way, why do we render the top bar when the experiment can be undefined?

2020-09-07 22:51 UTC, yanirs commented on components/GeneralPanel.tsx
> +  const canEditExperiment = experiment.status !== Status.Staging
This variable name is a bit confusing because we _can_ edit the experiment. Maybe change to `canEditPanel` or `canEdit`?

2020-09-07 22:51 UTC, yanirs commented on components/MetricAssignmentsPanel.tsx
> +  }
This is incorrect. Metrics can always be added for non-staging experiments.

2020-09-07 22:51 UTC, yanirs commented on components/ExperimentPageView.test.tsx
> +test('staging experiment shows correct features enabled in overview', async () => {
It's great to have more tests, but the duplication in this file makes it hard to see what gets tested and why. Can you please add a couple of local helpers to reduce duplication and make it clearer? Helpers that may work well are `renderExperimentPageView(status)` to replace lines 40-56 and their duplicates, and `checkButtonStates(expectedStates)` to replace lines 59-71 and their duplicates (where `expectedStates` is a mapping of the form `{editInWizard: true, run: false, conclusionEdit: null, ...}`).

I also think we can do without the snapshots, as the individual panels are already covered by snapshot tests.

2020-09-08 15:06 UTC, jessie-ross commented on components/GeneralPanel.tsx
> +  const canEditExperiment = experiment.status !== Status.Staging
:+1: Changing to `canEditGeneralPanel`

2020-09-08 16:33 UTC, jessie-ross commented on components/ExperimentPageView.tsx
> +            <Tooltip title={!canRunExperiment ? cantRunExperimentReason[experiment?.status as string] : ''}>
> By the way, why do we render the top bar when the experiment can be undefined?

That's a good point, I think ideally we would have it at the top but since we reload the data on every tab at the moment due to the router (plugging #212 here) it doesn't give a good UX for the tabs: https://d.pr/v/uW3T9K

I did just carry it forward from the original implementation but I have a feeling that this was the reasoning.

It is a pretty trivial change, easy to do now or later.

2020-09-09 05:20 UTC, yanirs approved these changes
See inline comment about unused variables, but other than that LGTM. :ship:

2020-09-09 05:20 UTC, yanirs commented on components/ExperimentPageView.test.tsx
> +test('staging experiment shows correct features enabled in overview', async () => {
So much clearer with the helper functions! :tada:

2020-09-09 05:20 UTC, yanirs commented on components/ExperimentPageView.test.tsx
> +  const { container: _container } = renderExperimentPageView({}, ExperimentView.Results)
Here and on other lines, what's the idea behind assigning the result to an unused variable?

```suggestion
  renderExperimentPageView({}, ExperimentView.Results)
```

2020-09-09 05:54 UTC, jessie-ross commented on components/ExperimentPageView.test.tsx
> +  const { container: _container } = renderExperimentPageView({}, ExperimentView.Results)
Oh just because I copy and pasted it... I will be more careful in the future but will just leave these as they are harmless.

2020-09-09 05:54 UTC, merged