Update allthethings
Automattic/abacus pull request #345
Opened 2020-09-25 14:27 UTC by withinboredom

This updates everything to the latest and greatest. In my testing, nothing looks broken even though there were some major upgrades.

## How has this been tested?

- Manual testing with mock data (locally or on Vercel)

2020-09-27 23:45 UTC, yanirs commented
@withinboredom looks like this broke the linting: See [build output](https://app.circleci.com/pipelines/github/Automattic/abacus/1308/workflows/cc8f016e-7f82-4516-b4db-e42c598cdacd/jobs/1396).

By the way, you can use `npm run verify` to run the CircleCI checks locally.

2020-09-28 09:26 UTC, withinboredom commented
Oh, nice. For these types of merges, I've usually found that you don't want to fix them in the same PR. It takes time to address the issues while new code is written that might break this branch. Instead, the "best" path forward is to usually ignore them, and address individual rule fixes in singular PR's by un-ignoring the rules.

Thoughts about that @yanirs, @jessie-ross ?

2020-09-28 09:37 UTC, yanirs commented
I think it's worth having a quick look at individual errors since some of them seem to be about rules that no longer exist and some fixes may be trivial. In general, adding new rules to the ignore list and handling them separately (i.e., adding an issue for later) makes sense, as it doesn't affect code quality. We need the build to pass, though. :slightly_smiling_face:

2020-09-29 08:44 UTC, jessie-ross commented
I take a very conservative approach to updates, it can be a major source of bugs and problems in JavaScript land.

We should be extra careful for non-dev dependencies.
Here that would be:
- `notistack`
- `formik-material-ui`
- `formik-material-ui-lab`

Some process around it might be:
- Read the change-logs.
- Wait until a Major rev has been around for a while before updating.
- Writing about the above checks in update PRs:

I've just had a look at the above and it seems like there has been no breaking changes that will affect us.
The new releases have been around for a month, which is newish but is fine for the size of these changes and the scope of use of these packages.

Lastly, I do think this is an important time to check all warnings and rule fixes as all our tooling is changing under us.
I think it is an important layer of safety in updates.

So LGTM once everything passes.

2020-10-05 22:28 UTC, withinboredom reviewed
I've left comments explaining how the rules changed the code and highlighted any areas changed for other reasons. There's a few shenanigans going on as well, so this PR isn't over. I'm happy to break this PR up into as little as six PRs:

1. Add returns types to everything
2. Add `void` before promises we don't await
3. (maybe before 1) fix the bugs highlighted in this PR
4. Fix the use of `any`
5. Actually update everything
6. Fix any remaining issues.

This would take longer, but be marginally safer. Or we can spend a few days reviewing this and merge as-is. There's a lot here, but I feel like the code is "safer."

2020-10-05 22:28 UTC, withinboredom commented on components/MetricsTable.test.tsx
> +  render(<MetricsTable metrics={Fixtures.createMetricBares(2)} onEditMetric={onEditMetric} />)
Same as above with `useStyles`, it just bothered me, so I removed the return :)

2020-10-05 22:28 UTC, withinboredom commented on components/RenderErrorView.tsx
> +export default function (props: { renderError: RenderError }): JSX.Element {
I don't remember why I changed this. But will change it back and see if I remember why I did it.

2020-10-05 22:28 UTC, withinboredom commented on components/__snapshots__/ExperimentDetails.test.tsx.snap
> +                title="Use \\\\\\"Edit in Wizard\\\\\\" for staging experiments."
More shenanigans.

2020-10-05 22:28 UTC, withinboredom commented on components/experiment-creation/Audience.tsx
>      field: { name, value: outerValue },
`outerValue` comes from formik and is of type `any` so need to ignore.

2020-10-05 22:28 UTC, withinboredom commented on components/experiment-creation/Audience.tsx
>                  placeholder={segmentAssignmentsField.value.length === 0 ? 'Search and select to customize' : undefined}
`segmentAssignmentsField.value` is of type `any`, so need to ignore.

2020-10-05 22:28 UTC, withinboredom commented on components/experiment-creation/Audience.tsx
> +                {formikProps.values.experiment.variations.map((variation, index) => {
This is now typed. See below.

2020-10-05 22:28 UTC, withinboredom commented on components/experiment-creation/ExperimentForm.test.tsx
> +          allocatedPercentage: '50',
By having to specify the return type, I discovered that `allocatedPercentage` is supposed to be a `string` not a number.

2020-10-05 22:28 UTC, withinboredom commented on components/experiment-creation/ExperimentForm.test.tsx
> +  newShapedExperiment.experimentId = (undefined as unknown) as number
you can't delete from a type when the value is required. So, I forcibly set them to undefined. Could also `ts-ignore` here.

2020-10-05 22:28 UTC, withinboredom commented on components/experiment-creation/Metrics.tsx
> +  const [metricAssignmentsField, , metricAssignmentsFieldHelperProps] = useField<MetricAssignment[]>(
I should change this back.

2020-10-05 22:28 UTC, withinboredom commented on components/experiment-creation/Metrics.tsx
> +  const [exposureEventsField, ,] = useField<EventNew[]>('experiment.exposureEvents')
Also this one.

2020-10-05 22:28 UTC, withinboredom commented on components/experiment-results/CondensedLatestAnalyses.tsx
> +          type: 'scatter' as const,
Must use `as const` now.

2020-10-05 22:28 UTC, withinboredom commented on config.ts
> +    authPath: 'http://example.com',
Instead of being forced to now handle the "sometimes null case" I just set it to `example.com`

2020-10-05 22:28 UTC, withinboredom commented on lib/form-data.ts
> +}
As mentioned above, these are now typed due to having to specify return types. This is good because it resulted in discovering the variation split being a `string` and not a number. I'm pretty sure a form input will translate a number to a string just fine if we wanted to go that route.

2020-10-05 22:28 UTC, withinboredom commented on lib/form-data.ts
> +    props: Object.entries(exposureEvent.props as Record<string, unknown>).map(([key, value]) => ({ key, value })),
`as object` or `as {}` is no longer allowed, instead use `Record<string unknown>`

2020-10-05 22:28 UTC, withinboredom commented on lib/schemas.test.ts
> +/* eslint-disable @typescript-eslint/no-unsafe-member-access */
This is needed since we use `any`'s to test the schema.

2020-10-05 22:28 UTC, withinboredom commented on lib/schemas.ts
>      return !(metricFull.parameterType === MetricParameterType.Conversion && !metricFull.eventParams)
It's debatable whether we should do proper assertions to turn the `any` into what we expect, but ignoring this for now.

2020-10-05 22:28 UTC, withinboredom commented on pages/auth.tsx
> +
Since query strings may be no value (`?`), a single value (`?key=value`), or an array (`?key[]=value1&key[]=value2`) we need to handle all these cases to resolve down to a single string.

2020-10-05 22:28 UTC, withinboredom commented on pages/auth.tsx
> +    const expiresInSeconds = toInt(authInfo.expires_in, 0) as unknown
I added a default fo when it's not a number.

2020-10-05 22:28 UTC, withinboredom commented on test-helpers/test-utils.tsx
> +/* eslint-disable @typescript-eslint/no-unsafe-return,@typescript-eslint/explicit-module-boundary-types */
There are a ton of errors in this file for use of `any`, so I just disabled it since it is't our fault :)

2020-10-05 22:28 UTC, withinboredom commented on utils/auth.ts
> +    ) as ExperimentsAuthInfo | null
I think it's probably safe to assume that it will be one of these two types. A todo would be to use `yup` to validate it to prevent malicious payloads.

2020-10-05 22:28 UTC, withinboredom commented on utils/data-loading.ts
> +      }
I rewrote this as a try/catch so coverage requirements would catch that the error case wasn't being tested. Previously, it considered it all one line.

2020-10-06 00:14 UTC, yanirs commented
> I'm happy to break this PR up into as little as six PRs [...] This would take longer, but be marginally safer. 

I think it may actually take less time as it'd be easy to approve the non-functional changes separately, but I'll @jessie-ross decide as the assigned reviewer. :slightly_smiling_face:

2020-10-06 00:16 UTC, yanirs commented on components/ExperimentsTable.tsx
> +    void router.push('/experiments/[id]', `/experiments/${rowData?.experimentId ?? ''}`)
I like it, as such promises were causing warnings in the tests.

2020-10-06 00:17 UTC, yanirs commented on components/GeneralPanel.test.tsx
> +            title="Use \\\\\\"Edit in Wizard\\\\\\" for staging experiments."
:joy:

2020-10-06 00:19 UTC, yanirs commented on components/experiment-creation/Audience.tsx
>      field: { name, value: outerValue },
Can we cast it to a known type instead?

2020-10-06 00:26 UTC, yanirs commented on api/utils.ts
> +  return JSON.parse(responseText) as unknown
Should we make this `Record<string, unknown>`?

2020-10-06 00:27 UTC, yanirs commented on components/Autocomplete.test.tsx
> +  // @ts-ignore
Yeah, there's an issue to suppress these eslint errors on all test files: #305.

2020-10-06 00:30 UTC, yanirs commented on components/ExperimentPageView.test.tsx
> +  const debug = view === ExperimentView.Debug
I see no harm in keeping them. :slightly_smiling_face:

2020-10-06 00:31 UTC, yanirs commented on components/ExperimentRunButton.tsx
> +  useStyles()
Yeah, there are a few of these lying around. No need to assign to an unused variable. :slightly_smiling_face:

2020-10-06 00:35 UTC, yanirs commented on components/MetricsTable.test.tsx
> +  render(<MetricsTable metrics={Fixtures.createMetricBares(2)} onEditMetric={onEditMetric} />)
It looks much better. :slightly_smiling_face:

2020-10-06 00:36 UTC, yanirs commented on components/__snapshots__/ExperimentDetails.test.tsx.snap
> +                title="Use \\\\\\"Edit in Wizard\\\\\\" for staging experiments."
\\\\\\\\\\\\\\\\\\\\\\\\\

2020-10-06 00:41 UTC, yanirs commented on components/experiment-results/CondensedLatestAnalyses.tsx
> +          type: 'scatter' as const,
It looks better than `'str' as 'str'` :slightly_smiling_face:

2020-10-06 00:44 UTC, yanirs commented on lib/schemas.ts
>      return !(metricFull.parameterType === MetricParameterType.Conversion && !metricFull.eventParams)
It might be better to suppress on the file level and explain why with an inline comment.

2020-10-06 00:47 UTC, yanirs commented on pages/auth.tsx
> +    const expiresInSeconds = toInt(authInfo.expires_in, 0) as unknown
Should it still be `as unknown` then?

2020-10-06 00:47 UTC, yanirs commented on pages/auth.tsx
> +    const getStringFromQueryString = (str: string | string[] | undefined, def = 'unkown'): string => {
`unkown` -> `unknown`?

2020-10-06 00:50 UTC, withinboredom commented on components/experiment-creation/Audience.tsx
>      field: { name, value: outerValue },
Maybe, but I didn't investigate what that type would be. It would be better if we either checked to see if the project has a `@types/` repo or just wait for them to export their types.

2020-10-06 00:51 UTC, withinboredom commented on pages/auth.tsx
> +    const expiresInSeconds = toInt(authInfo.expires_in, 0) as unknown
Yes, because it's `unknown` because it may still not be a number :D what joy javascript is... (aka `NaN` which is still a number but not numeric, IIRC)

2020-10-06 00:53 UTC, withinboredom commented on api/utils.ts
> +  return JSON.parse(responseText) as unknown
Trust me, this is simpler :) and it may be a non-object (aka, `null`). We also return `undefined` which complicates things...

2020-10-06 01:04 UTC, yanirs commented on utils/data-loading.ts
> +      }
Maybe we can also make the `isSubscribed` case more explicit?

```suggestion
      if (isSubscribed) {
        try {
          setData(await createDataPromise())
        } catch (error) {
          setError(error)
        } finally {
          setIsLoading(false)
        }
      } else {
        try {
          await createDataPromise()
        } catch (error) {}
      }
```

2020-10-06 01:09 UTC, yanirs commented
> > I'm happy to break this PR up into as little as six PRs [...] This would take longer, but be marginally safer.
> 
> I think it may actually take less time as it'd be easy to approve the non-functional changes separately, but I'll @jessie-ross decide as the assigned reviewer. :slightly_smiling_face:

I did a quick pass because I was curious and it's actually not too bad when marking files as viewed:

![image](https://user-images.githubusercontent.com/3952615/95147474-2e7f2100-07c4-11eb-9166-8750983bddfd.png)

This would still get stale quickly, so it may be worth cherry picking the bulk of this PR if some discussions drag on.

2020-10-06 01:16 UTC, yanirs commented on api/utils.ts
> +  return JSON.parse(responseText) as unknown
We don't return `null` from the API, only an empty response or an object. We can change the return type of the function to `Promise<undefined | Record<string, unknown>>` to account for the `undefined` case.

I don't feel _too_ strongly about it, but it seems like it's worth being more specific where possible.

2020-10-06 01:21 UTC, yanirs commented on api/utils.ts
> +  return JSON.parse(responseText) as unknown
Oh, and we can also return an empty object instead of `undefined` when the response is empty to make it cleaner.

2020-10-06 06:18 UTC, jessie-ross commented on api/MetricsApi.ts
> +  const { metrics } = await metricBareResponse.validate(
I would prefer to create inline schemas for incidental data types like response objects so we can keep our core data types to a minimum:

```const { metrics } = await yup.object({ metrics: yup.array(metricBareSchema) }).validate(``` 

And if we don't we should follow our naming convention for schemas `metricBareResponseSchema`.

2020-10-06 06:19 UTC, jessie-ross commented on api/SegmentsApi.ts
> +  const { segments } = await segmentResponseSchema.validate(await fetchApi('GET', '/segments'), { abortEarly: false })
See my comment on the metric endpoint

2020-10-06 06:22 UTC, jessie-ross commented on components/Autocomplete.test.tsx
> -  const options: AutocompleteItem[] = []
Wow I would find this super annoying but ok

2020-10-06 06:29 UTC, jessie-ross commented on components/ExperimentRunButton.tsx
> +  useStyles()
There shouldn't be any side effect here so this line can be removed.

I leave them in as eventually every element needs styles and I'd have to add all this code back in. It is useful for rapid UI development.

2020-10-06 06:37 UTC, jessie-ross commented on components/ExperimentStatus.tsx
> +function ExperimentStatus({ status }: { status: Status }): JSX.Element {
I am surprised these JSX.Element types work, there must be some typescript magic going on - typescript still knows what props and prop types our components accept.

2020-10-06 06:59 UTC, jessie-ross commented on components/RenderErrorView.tsx
> +export default function (props: { renderError: RenderError }): JSX.Element {
This should be fine

2020-10-06 09:19 UTC, jessie-ross requested changes
Phew! I made it! See my comments.

I don't mind reviewing it like this, but for the future a good way to split this is by package, we could update all the other packages and then do typescript and eslint separately.

And then with eslint if there are new rules enabled by default we can disable them and then add them on one by one along with its associated changes.

2020-10-06 09:19 UTC, jessie-ross commented on utils/data-loading.ts
> +      }
@yanirs I don't think this will work as it is possible for `isSubscribed` to have changed while waiting for the promise resolution, and we want the value at the execution time of `setX`. Unfortunately the new await syntax makes it a little less obvious that this is happening in a different "queued sub-task", and where exactly that line is.

@withinboredom I am surprised the inline `if` statements here pass our code conventions? We don't do that anywhere AFAIK.

2020-10-06 10:21 UTC, withinboredom commented on api/MetricsApi.ts
> +  const { metrics } = await metricBareResponse.validate(
Oh nice, didn't know that was possible but it makes sense!

2020-10-06 10:28 UTC, withinboredom commented on utils/data-loading.ts
> +      }
> I am surprised the inline if statements here pass our code conventions? We don't do that anywhere AFAIK.

I always write inline ifs unless it's more than one statement and let autoformat / linters fix them if they aren't allowed (habit from writing C/C++ for years) but maybe the rules changed with the updated eslint and it wasn't caught. I'll update the code here.

2020-10-06 10:30 UTC, withinboredom commented on api/utils.ts
> +  return JSON.parse(responseText) as unknown
See https://github.com/Automattic/abacus/pull/339/commits/e43cf76b6222543cfddc69d0b0e93852393fb5f0#r493677967

2020-10-06 10:43 UTC, jessie-ross commented on utils/data-loading.ts
> +      }
Yeah I generally prefer having stable syntax (syntax that doesn't change if the semantics doesn't), this means less editing and better diffs.

2020-10-07 10:21 UTC, withinboredom commented on utils/data-loading.test.ts
> +      console.error = jest.fn((d) => originalConsoleError(d))
We're not expecting the error to actually occur, but if it does, it's useful to output it and jest will catch it as well. I ran into errors being output in these tests that shouldn't have been so I added this to see what the errors were so I could fix them.

2020-10-07 14:06 UTC, jessie-ross commented on pages/auth.tsx
> +      setError(`An unknown error has occurred: Missing hash in auth callback url.`)
Lol nice catch!

2020-10-07 14:11 UTC, jessie-ross approved these changes
LGTM! 
🛸 🛸 🛸

2020-10-07 14:12 UTC, merged