WIP: Add event autocompletions
Automattic/abacus pull request #352
Opened 2020-10-01 11:43 UTC by withinboredom

This adds event and props autocomplete to the experiment wizard.

## How has this been tested?

- Automated tests that cover added/changed functionality
- Manual testing with production data (locally)
- Manual testing with mock data (locally or on Vercel)

2020-10-01 14:52 UTC, withinboredom commented on components/experiment-creation/Metrics.tsx
> +const EventEditor = ({
This block of code is pulled from below because hooks cannot be called in a branch and must be top-level. So, I pulled it into it's own component. This bit is probably easier to view from this [commit view](https://github.com/Automattic/abacus/pull/352/commits/b2fff2b123dc552dadcfaca422e0ae927c6acffa).

2020-10-01 14:52 UTC, withinboredom commented on components/experiment-creation/Metrics.tsx
> +  >
I wasn't sure if this should be broken into it's own classes. It seemed simpler to do it this way, but it makes sense either way.

2020-10-01 14:52 UTC, withinboredom commented on components/experiment-creation/Metrics.tsx
> +  const { isLoading, data: propList } = useDataSource(getPropCompletions(exposureEvent.event), [exposureEvent.event])
Can add this as a comment, but it seems pretty obvious: had to add this disable because we know the function returned by `getPropCompletions` can't rely on anything more than the string we pass to it. In fact, the error given makes no sense (unless it's trying to prevent people from creating a closure on deps in the same function, which I guess makes sense).

We also need to make the actual string a dep (vs the object) because formik passes a new object every time, even though it's exactly the same value.

2020-10-01 17:16 UTC, jessie-ross requested changes
Main changes requested:
- Having `getPropsCompletions` return the data rather than a function
- Separating the classes.

See comments for more info, other than that this is looking good.

2020-10-01 17:16 UTC, jessie-ross commented on api/AutocompleteApi.ts
> +export function getPropCompletions(eventName: string): () => Promise<AutocompleteItem[]> {
Yeah the code at this level shouldn't need to be involved with how it is used, it should just return a promise of the data rather than another function that returns a promise.

2020-10-01 17:16 UTC, jessie-ross commented on components/experiment-creation/Metrics.tsx
> +  const { isLoading, data: propList } = useDataSource(getPropCompletions(exposureEvent.event), [exposureEvent.event])
Yeah I think the standard way of doing this is to create a function here that returns a promise, that will make the error go away and allow proper dep checking.

E.g.:
```
const { isLoading, data: propList } = useDataSource(() => getPropCompletions(exposureEvent.event), [exposureEvent.event])
```

2020-10-01 17:16 UTC, jessie-ross commented on components/experiment-creation/Metrics.tsx
> +}: {
This is a reasonable midway abstraction, but if you feel like it now you should be able to get the props down to just: `{ name, onDelete }`.

That will help it on it's way to being moved to the metric edit/add form.

2020-10-01 17:16 UTC, jessie-ross commented on components/experiment-creation/Metrics.tsx
> +const EventEditor = ({
👍  Makes sense, and this is something we will want to do anyway.

2020-10-02 10:28 UTC, withinboredom commented on api/AutocompleteApi.ts
> +    } catch (er) {
> but we are conflating any error here as missing data and not reporting actual errors to the user.

I made this decision after thinking about the types of errors a user may encounter:
1. unauthorized: they need to login but there should be (hopefully) better systems to detect this and inform the user. Perhaps we need to rethrow here so that system catches it.
2. disconnected: there's no point in displaying an error about that since we don't prevent the user from entering whatever value they want and we don't have any way to re-fetch once they do reconnect. Also, they likely wouldn't have been able to select an event in the first place and the error would be reported there.
3. server error (500): things will get logged on the server. There's nothing the user can do except notify us, but we should already be monitoring those logs. They can still enter the props, albeit, manually.
4. not found: we cover this case.

There's no disaster by ignoring most errors and the user can/should be able to continue.

2020-10-02 10:31 UTC, withinboredom commented on api/AutocompleteApi.ts
> +export function getPropCompletions(eventName: string): () => Promise<AutocompleteItem[]> {
I think that makes sense with the changes [you suggested here](https://github.com/Automattic/abacus/pull/352#discussion_r498392652)

2020-10-02 14:13 UTC, jessie-ross commented on api/AutocompleteApi.ts
> +export function getPropCompletions(eventName: string): () => Promise<AutocompleteItem[]> {
Yep that's what I meant, it would probably help if I had explicitly linked the two.

2020-10-09 09:38 UTC, jessie-ross commented
I'll merge this guy once/if CRA manages to land

2020-10-13 07:06 UTC, jessie-ross commented
I've just merged the master into here so @withinboredom doesn't have to deal with the restructure.

2020-10-14 06:05 UTC, jessie-ross commented
@withinboredom Is this ready to merge?

2020-10-14 14:03 UTC, withinboredom commented
@jessie-ross Still blocked by your last review, feel free to change it and merge away :p :D

2020-10-15 14:27 UTC, jessie-ross commented
Not sure if this needs a second review, I have moved some of the UI code out of the API, fixed the tests as a result and fixed some warnings, and removed the unused schemas.

2020-10-15 14:27 UTC, jessie-ross commented
@withinboredom I am going to accept it, if you think it is good feel free to merge.

2020-10-15 14:27 UTC, jessie-ross approved these changes

2020-10-15 22:56 UTC, merged

2020-10-16 00:03 UTC, aaronyan commented
Helps resolve #323!