Add participants graph
Automattic/abacus pull request #353
Opened 2020-10-01 18:58 UTC by jessie-ross

**This PR adds a participants graph.**
- Full width for now under the metric graphs
- Includes: Totals, Not Final, Variations
- Not sure it belongs here, above the metrics list?

For a screenshot see: 

Resolves #97 

## How has this been tested?

- Automated tests that cover added/changed functionality
- Manual testing with production data (locally)

2020-10-02 03:23 UTC, yanirs requested changes
As noted on the P2 thread, let's make it a single graph at the top of the page, based on the counts from the primary metric. We don't need to plot the not final counts as they're only interesting on a per-metric level for the last analysis date – it’s an indication of how much the results may change.

2020-10-03 01:40 UTC, aaronyan commented
Looking great! +1 to removing `Not Final` from the participants graph. I would also remove the `Total` series, because I think the participants graphs is mainly comparing the two variations.

2020-10-05 05:34 UTC, jessie-ross commented
## Update

All the feedback has hopefully been taken on, see pbmo2S-vR-p2#comment-1168 for more info.

2020-10-05 05:44 UTC, yanirs commented on components/experiment-results/CondensedLatestAnalyses.tsx
> +import * as Visualisations from '@/lib/visualisations'
Let's stick to American spelling for consistency (`visualizations`). :slightly_smiling_face:

2020-10-05 05:45 UTC, yanirs commented
Loading the result page on Vercel yields an error: https://abacus-git-add-participant-graph.a8c.vercel.app/experiments/2/results. Is this a general problem or specific to the Swagger API results?

2020-10-05 13:20 UTC, withinboredom approved these changes
LGTM, just needs the renaming to US-EN (which I didn't even notice).

2020-10-05 13:25 UTC, jessie-ross commented
> Loading the result page on Vercel yields an error: https://abacus-git-add-participant-graph.a8c.vercel.app/experiments/2/results. Is this a general problem or specific to the Swagger API results?

Yeah this is pretty minor to cover for either way. 

> Let's stick to American spelling for consistency (visualizations). 🙂

Sure! 🇺🇸 

---

I'm just holding of for Aarons feedback on the total.

2020-10-05 23:14 UTC, yanirs commented
Looking at https://abacus-git-add-participant-graph.a8c.vercel.app/experiments/1/results now that it's fixed, it's a bit confusing with a single day of data, but I'll open a separate issue.

2020-10-05 23:14 UTC, yanirs approved these changes

2020-10-05 23:15 UTC, merged