Add better code examples
Automattic/abacus pull request #368
Opened 2020-10-14 14:02 UTC by withinboredom

Adds some awesome code examples for people to basically copy/paste to their projects.

## How has this been tested?

- Automated tests that cover added/changed functionality
- Manual testing with production data (locally)
- Manual testing with mock data (locally or on Vercel)
- Additional manual testing instructions (please specify):

2020-10-16 14:04 UTC, jessie-ross commented on src/components/ExperimentCodeSetup.tsx
> +        if (experiment.name.startsWith('lohp')) {
Should `lohp` be it's own platform?

2020-10-16 14:42 UTC, withinboredom commented on src/components/ExperimentCodeSetup.tsx
> +        if (experiment.name.startsWith('lohp')) {
Not imo, because the lohp experiments likely affect other platforms (like Guides, or enabling a feature in calypso).

2020-10-16 14:46 UTC, jessie-ross requested changes
Sorry I got to this late, I think I was waiting for this PR to go green before reviewing.

2020-10-16 14:46 UTC, jessie-ross commented on src/components/ExperimentCodeSetup.tsx
> +    switch (experiment.platform) {
This should be a named function `experiment -> actualPlatform`.

Possibly should sit with other business logic in `/lib/experiments.ts`.

2020-10-16 14:46 UTC, jessie-ross commented on src/components/ExperimentCodeSetup.tsx
> +        <Tab label={'React'} />
I think it makes sense to call this "Calypso" rather than "React".

2020-10-16 14:46 UTC, jessie-ross commented on src/components/ExperimentCodeSetup.tsx
> +        return 0
Maybe let's add in an `enum` for these?

2020-10-16 14:46 UTC, jessie-ross commented on src/components/ExperimentCodeSetup.tsx
> +  const treatmentVariation = experiment.variations.flatMap((x) => (x.isDefault ? null : x.name))[0] ?? 'treatment'
I suggest passing around variations as variation data structures rather than names as it makes this simpler and more extensible:

```suggestion
  const defaultVariation = experiment.variations.find(x => x.isDefault)
  const treatmentVariation = experiment.variations.find(x => !x.isDefault)
  
  // istanbul ignore next; typeguard, this is ensured by our schema
  if (!defaultVariation || !treatmentVariation) {
    throw new Error('Missing variations.')
  }
```


( 😅  It has taken me too long to figure out how to do these GitHub change suggestions.)

2020-10-16 14:46 UTC, jessie-ross commented on src/components/ExperimentCodeSetup.tsx
> +import Highlight from 'react-syntax-highlighter'
It looks like `react-syntax-highlighter` is only a transitive dependency? it should be added to `package.json`.

I like to do a maintenance case for new deps, something like this:
- How critical is this library for us?
- Will we get tied to this lib? 
- Is it well maintained?

I have taken a look at this lib and this is the maintenance case:
- Doesn't provide a critical feature.
- Very easy to replace.
- Been around for two years, maintainers are active.

2020-10-16 14:49 UTC, withinboredom commented
> I think I was waiting for this PR to go green before reviewing.

Not to worry, I was expecting to be able to merge the lohp stuff days ago, which it appears it will now be much much longer, so I don't mind sitting on this until that's merged.

2021-01-21 20:18 UTC, yanirs commented
Closing this since it's quite stale. Can reopen in the future or start a new PR.

2021-01-21 20:18 UTC, closed without merging

2021-01-26 17:50 UTC, withinboredom commented
FWIW, you're not the author. Asking to close it in a comment or DM is the proper etiquette. Closing this is fine though.

2021-01-26 20:59 UTC, yanirs commented
> FWIW, you're not the author. Asking to close it in a comment or DM is the proper etiquette. Closing this is fine though.

I don't think it matters much in terms of etiquette for both issues and PRs, as reopening is just a click away. :slightly_smiling_face:

2021-01-26 21:46 UTC, aaronyan commented
Let's recognize that @withinboredom prefers a comment or DM to request to close. I think it's valuable to share how we prefer to work and acknowledge them.

Let's also recognize @yanirs being proactive in looking through and cleaning things up; I think the intention of closing was good. We have lots of old and sometimes repeat issues and PRs, so it's nice to move things forward or close things out.