Top Level Result Info
Automattic/abacus pull request #454
Opened 2021-01-20 17:42 UTC by jessie-ross

**This PR adds top level info to Experiment Results:**
- Top Level Stats
   - Displays max participant count over strategies
   - Display primary metric recommendation
- Health Traffic lights
   - Display sample ratio, sampler spammer ratio, crossovers
   - In debug mode show in depth details in added panel below
   - Link to new wiki page for details 

Future PRs (after the Calypso Client):
- Adding stopping time and Guard rail metrics

## How has this been tested?

- Automated tests that cover added/changed functionality
- Manual testing with production data (locally)

2021-01-20 17:49 UTC, jessie-ross commented on src/components/experiments/single-view/ExperimentDisableButton.tsx
> +          <Typography variant='h5' component='h3'>
Fixing a warning

2021-01-20 17:49 UTC, jessie-ross commented on src/components/experiments/single-view/ExperimentRunButton.tsx
> +          <Typography variant='h5' component='h3'>
Fixing a warning

2021-01-20 20:14 UTC, withinboredom requested changes
All in all, this looks good. However, it may be worth taking a few lines at the beginning of the code path to assert sanity (remove `null` as a possible value) and would go a long way to cleaning up and making the code more readable/maintainable.

This is a big diff. It might be a good idea to do the traffic light calculations as a separate diff.

2021-01-21 01:08 UTC, jessie-ross commented on src/utils/math.ts
> +  const variance = n * p * (1 - p)
I like the version in terms of `n` and `p` as it is more meaningful than the relationship between `variance` and `mean`.

2021-01-21 01:08 UTC, jessie-ross commented on src/utils/math.test.ts
> +      expect(Math.abs(binomialProbValue(1, 30, 0.5) - 0.000002)).toBeLessThan(aSmallValue)
No I don't think so, it needs to be "small enough" for our intents and purposes but can't be too small as this is just an approximation.

2021-01-21 01:11 UTC, jessie-ross commented on src/components/experiments/single-view/results/ActualExperimentResults.tsx
> +    const xUsers = latestPrimaryMetricAnalysis?.participantStats[`variation_${variation.variationId}`]
Ah these are standard variables for a binomial trial with `x` successes out of `n` trials, I should probably document that/change them.

2021-01-21 01:16 UTC, jessie-ross commented on src/components/experiments/single-view/results/ActualExperimentResults.tsx
> +    userSampleRatioMinProbValue < 0.01 ? TrafficLightColor.Red : TrafficLightColor.Green
This particular case is a result of running `min` over a list - typescript can't check that a list has elements, and if there are no elements `min` returns `null`. The introduction of `?? 0` is purely to please typescript.

2021-01-21 01:56 UTC, yanirs commented on src/components/experiments/single-view/results/ActualExperimentResults.tsx
> +  // ### Top Level Stats
Yeah, I think that a lot of these calculations should be pulled out to utility functions and unit tested.

2021-01-21 01:58 UTC, yanirs commented on src/components/experiments/single-view/results/ActualExperimentResults.tsx
> +    const xUsers = latestPrimaryMetricAnalysis?.participantStats[`variation_${variation.variationId}`]
Yeah, probably change it to more informative names. Names like `p`, `n`, and `x` have way too many meanings. 

Also, this introduces `users` as a new term, which we've been intentionally avoiding.

I'd go with:

* `p` -> `expectedVariationProbability`
* `nUsers` -> `totalParticipants`
* `xUsers` -> `variationParticipants`

2021-01-21 02:00 UTC, yanirs commented on src/components/experiments/single-view/results/ActualExperimentResults.tsx
> +    userSampleRatioMinProbValue < 0.01 ? TrafficLightColor.Red : TrafficLightColor.Green
We can also please TypeScript by casting with `as <type>`, which is more self-documenting in this case.

2021-01-21 02:00 UTC, yanirs commented on src/components/experiments/single-view/results/ActualExperimentResults.tsx
> +        // istanbul ignore next; Debug only
Debug mode should be tested, as it's also meant for experiment reviewers.

2021-01-21 02:02 UTC, yanirs commented on src/components/experiments/single-view/results/TrafficLightStatus.tsx
> +export default function TrafficLightStatus({ color, label }: { color: TrafficLightColor; label: string }): JSX.Element {
I'm not colour blind and I find it hard to see the difference between the red and green here. We should have another visual indication and not rely on colour alone, e.g., :heavy_check_mark: :warning: :stop_sign: instead of colours.

2021-01-21 02:06 UTC, yanirs commented on src/components/experiments/single-view/results/ActualExperimentResults.tsx
> +    const xCrossovers =
As part of pulling this code out to helpers, it'd be good to also reduce duplication here as all these conditionals are very hard to parse.

2021-01-21 02:10 UTC, yanirs commented on src/components/experiments/single-view/results/ActualExperimentResults.tsx
> +              <TrafficLightStatus color={userSampleRatioTrafficLight} label='Sample User Ratios' />
As above, let's stick to talking about participants. Also, as this file is getting massive, it may be better to pull this part out to a separate component.

In addition, I think it'd be good to show more information on _why_ the label is what it is, e.g., change to `Participant SRM probability: <>`.

2021-01-21 02:13 UTC, yanirs commented on src/components/experiments/single-view/results/ActualExperimentResults.tsx
> +    userSampleRatioMinProbValue < 0.01 ? TrafficLightColor.Red : TrafficLightColor.Green
+1, and please test the "trivial" cases, which would become easier when this is broken up to helpers and components.

2021-01-21 02:29 UTC, yanirs requested changes
I've only skimmed the code, but I agree with a lot of what Rob said.

Main top-level comments regarding the panel's content:

* We need a stronger visual indicator than colour
* It'd be good to include more information than the recommendation (i.e., the probabilities and ratios)
* We should also include an SRM warning for exposed participants

Main top-level comments regarding the code:

* This should be broken up and unit tested, which would make it easy to eliminate all/most of the `istanbul ignore` comments and also make the code more readable. Much of the logic can be separated from the component into helpers.
* As Rob noted, this is a pretty big PR, which would be easier to review if it's broken up.

2021-03-07 12:03 UTC, jessie-ross commented on src/components/experiments/single-view/results/__snapshots__/ExperimentResults.test.tsx.snap
> +               as at
Uhm, I think `as at` is better here as we want the connotation of a snapshot: https://english.stackexchange.com/a/112771

2021-03-07 12:13 UTC, jessie-ross commented on src/components/experiments/single-view/results/ActualExperimentResults.tsx
> +        x?.participantStats?.['total'] ?? 0,
I've cleaned this up a bit (and removed the `participantsStats` check), see:
https://github.com/Automattic/abacus/pull/454/files#diff-6912e9b6b168daffa48dc35b58ada31ef27c57e60353cabbd01397c2a28f9966R212-R224

We are returning zero in either strategy missing or invalid data response (missing `total`). I don't think it is worth it to add two test cases just to get coverage here?

2021-03-08 12:37 UTC, jessie-ross commented
## Update

- Removed the traffic light code.
- Refactored the Recommendation code:
   - Added `AggregateRecommendation` type.
   - Added `getAggregateRecommendation(analyses: Analyses[])`
   - Added `AggregateRecommendationDisplay` replacing `RecommendationString`.

There is a lot here but 95% of the changes now are refactoring the recommendation code, most of which are tests and the new functions and types which should be straight forward.

2021-03-08 13:05 UTC, jessie-ross commented on src/lib/analyses.ts
> +export function getAggregateRecommendation(analyses: Analysis[]): AggregateRecommendation {
The recommendation code is now all in once place and separate from the UI code.

2021-03-09 01:01 UTC, yanirs commented
@jessie-ross it's been a long time since either @withinboredom or I looked at this PR. Given that we both suggested breaking it up back in January, it'd be good to separate refactoring changes to a different PR so this is easier to review and discuss.

2021-03-09 02:02 UTC, jessie-ross commented
> Given that we both suggested breaking it up back in January, it'd be good to separate refactoring changes to a different PR so this is easier to review and discuss.

Yeah this is actually the broken up version, after moving AggregateRecommendation out to it's own file and refactoring for it, but sure I will break it up further. 

> Given the time that's passed and the changes made, I'm not sure what the PR is supposed to do at this point, but looking at Vercel, the big empty panel doesn't look right.

Yeah decided to leave it in as an intermediate change to the overall layout, but sure I can remove it.

2021-03-09 05:02 UTC, jessie-ross commented
Closed by #471, with traffic lights to be included in a future PR

2021-03-09 05:02 UTC, closed without merging