Add/significance data
Automattic/abacus pull request #557
Opened 2021-06-23 18:56 UTC by jessie-ross

**This PR adds practical and statistical significance data to AggregateRecommendation:**
- Needed for #524 [using my version of the spreadsheet](https://docs.google.com/spreadsheets/d/1CiumVCKJD0gl4tuTiOvljYHFX12M7yiIwBKitIkyAO0/edit?usp=sharing)  (see also @aaronyan comment to @yanirs in Aarons spreadsheet), see the extra part of the table at the end and how the two columns uniquely identify a message.
- Wanted central and testable location to put this data.
- Since most of the work here is added testing and the same testing is needed for moving the recommender code here I thought I would move it here anyway, but I forgot I didn't have access to `metric.higherIsBetter` (see code comments) so it is very close but incomplete. I think it is a small diff so I might make it tomorrow.

## How has this been tested?

WIP

- Automated tests that cover added/changed functionality
- Manual testing with production data (locally)
- Manual testing with mock data (locally or on Vercel)
- Additional manual testing instructions (please specify):

2021-06-24 04:48 UTC, yanirs commented on src/lib/analyses.ts
> +export enum PracticalSignificanceStatus {
Can you please explain the need for this? The recommendation reason already maps nicely to the explanations we discussed.

2021-06-24 04:52 UTC, yanirs commented on src/lib/analyses.ts
> +  // const chosenVariation = analysis.metricEstimates.diff.bottom > 0 === metric.higherIsBetter ? nonDefaultVariation : defaultVariation
Why would this be needed? For the purpose of the explanations we discussed, we only care about whether the value is different from zero. Statistical significance shouldn't be used for the recommendation's bottom line.

2021-06-24 04:59 UTC, jessie-ross commented on src/lib/analyses.ts
> +  // const chosenVariation = analysis.metricEstimates.diff.bottom > 0 === metric.higherIsBetter ? nonDefaultVariation : defaultVariation
It isn't, practical significance is used here, we are just seeing which side of 0 we are on.

2021-06-24 05:09 UTC, yanirs commented on src/lib/analyses.ts
> +  // const chosenVariation = analysis.metricEstimates.diff.bottom > 0 === metric.higherIsBetter ? nonDefaultVariation : defaultVariation
Then why do we need `higherIsBetter`?

2021-06-24 05:19 UTC, jessie-ross commented on src/lib/analyses.ts
> +export enum PracticalSignificanceStatus {
Practical and Statistical significance are what we care about when generating the recommendation/explanation, it is also the main thing we are communicating with these added explanations. It will also be used in other areas of the UI such as in highlighting significant values.

See the table at the end of https://docs.google.com/spreadsheets/d/1CiumVCKJD0gl4tuTiOvljYHFX12M7yiIwBKitIkyAO0/edit#gid=0

- Statistical maps to explanation 1
- Practical maps to explanation 2
- We can easily generate the overview sentence.

Being able to branch the code on practical and statistical significance levels makes the control flow simpler and the code much easier to understand - e.g. a result is inconclusive because a value might be practically significant vs a result is inconclusive because CI overlaps with ROPE. We want to move from the implementation detail of CI relation to ROPE and 0 to the higher level concept of statistical and practical significance.

The alternative is having a massive switch statement on the 'reason' codes, without the ability to factor together similar explanations, at least not without adding more complexity. I am not a fan of the reason codes, by conflating the two dimensions of significance together we are losing clarity and cleanness of our code.

Further, for this slight reframe we get the ability to remove `recommender.py` for free - 400 lines of code complicating the ETL.

2021-06-24 05:49 UTC, yanirs commented on src/lib/analyses.ts
> +export enum PracticalSignificanceStatus {
Moving the recommendation logic to Abacus makes sense &ndash; I'm on board with that.

I think that the problem is with the idea of "maybe" being a valid answer to "is this practically significant?" It's not really saying much, and it means that the `practicallySignificant?` field has four possible values (including undefined). It'd be better to keep it as a boolean with:

* `true`: The difference is practically significant with high certainty.
* `false`: The difference isn't practically significant with high certainty.
* `undefined`: Uncertainty is too high to say anything about practical significance.

This would also simplify the code, as the focus will be on setting the decision based on the analysis rather than repeating the full analysis structure creation.

2021-06-24 06:00 UTC, jessie-ross commented on src/lib/analyses.ts
> +  // const chosenVariation = analysis.metricEstimates.diff.bottom > 0 === metric.higherIsBetter ? nonDefaultVariation : defaultVariation
We need `higherIsBetter` to know which variation is better - to get the `chosenVariationId`.

We need to know whether the diff is positive or negative _and then_ whether positive/negative is a good thing.

2021-06-24 06:05 UTC, jessie-ross commented on src/lib/analyses.ts
> +export enum PracticalSignificanceStatus {
I am somewhat against the boolean/undefined values - it makes it very easy to make errors as we would be using them in a rather unorthodox way, especially with both false and undefined being falsey. 

Would using 'Uncertain' instead of 'Maybe' sweeten the deal?

2021-06-24 06:09 UTC, jessie-ross commented on src/lib/analyses.ts
> +  // const chosenVariation = analysis.metricEstimates.diff.bottom > 0 === metric.higherIsBetter ? nonDefaultVariation : defaultVariation
In case it isn't clear, these extra 3 lines of code lets us replace `recommender.py`.

2021-06-24 06:11 UTC, jessie-ross commented on src/lib/analyses.ts
> +export enum PracticalSignificanceStatus {
> it means that the practicallySignificant? field has four possible values (including undefined, which is sort of like "maybe").

It is only undefined for missingAnalysisData, for which we show nothing.

2021-06-24 06:16 UTC, yanirs commented on src/lib/analyses.ts
> +  // const chosenVariation = analysis.metricEstimates.diff.bottom > 0 === metric.higherIsBetter ? nonDefaultVariation : defaultVariation
Yeah, that's the bit of context I missed &ndash; I thought this PR was only about supporting the explanations.

2021-06-24 06:27 UTC, yanirs commented on src/lib/analyses.ts
> +export enum PracticalSignificanceStatus {
> Would using 'Uncertain' instead of 'Maybe' sweeten the deal?

Yeah, that's much better. 

> It is only undefined for missingAnalysisData, for which we show nothing.

Also for "manual analysis required". :slightly_smiling_face: 

> Further, for this slight reframe we get the ability to remove `recommender.py` for free - 400 lines of code complicating the ETL.

I just had a look and `recommender.py` is actually 160 lines, with about half of them being documentation. While I'm on board with moving the logic here, we shouldn't lose the documentation, as this stuff isn't trivial. I know that this is still a WIP, but can you please use the opportunity to fully document the recommendation code?

2021-06-24 06:49 UTC, jessie-ross commented on src/lib/analyses.ts
> +export enum PracticalSignificanceStatus {
> 400 lines of code 

I'm including the test code.

2021-06-25 02:13 UTC, yanirs commented on src/lib/schemas.ts
> +    higherIsBetter: yup.boolean().defined(),
Not sure if that's already the plan since this is still WIP, but it'd be good to have a separate PR with the retirement of `MetricBare`.

2021-06-25 02:57 UTC, jessie-ross commented on src/lib/schemas.ts
> +    higherIsBetter: yup.boolean().defined(),
Yep that's the plan, just doing the minimal here so I can focus on this change.

2021-06-29 02:10 UTC, yanirs commented on src/components/experiments/single-view/results/__snapshots__/ExperimentDebug.test.tsx.snap
> +                      Deploy either variation
Why have these snapshot changed?

2021-06-29 04:07 UTC, yanirs requested changes
I haven't fully looked through the tests, but here are my top-level comments so far:
- This is a pretty big PR. I'm guessing there may be an issue with the dummy data, but changing it to not affect existing snapshot tests would make reviewing easier.
- I think that `getAggregateRecommendation()` should be broken up and focused on a single recommendation to make it easier to work with and maintain. It may have made sense when we had less logic in Abacus, but doing so much in the function opens the door to many subtle bugs and plenty of confusion.
- I think it'd be better to revert the name changes from https://github.com/Automattic/abacus/commit/ab92d6586e7f613b51b0755b6b5df36383645b54 
- Documentation of exported functionality should be detailed enough for people who don't come with much context.

2021-06-29 04:12 UTC, jessie-ross commented on src/components/experiments/single-view/results/__snapshots__/ExperimentDebug.test.tsx.snap
> +                      Deploy either variation
Yeah we used the recommendation object before and now we use metricEstimates - they aren't consistent in the fixtures.

2021-06-29 04:18 UTC, jessie-ross commented on src/lib/analyses.ts
> +      ...new Set(
Good point, this comes from the original implementation.

2021-06-29 04:24 UTC, jessie-ross commented on src/lib/analyses.ts
>  export function getAggregateRecommendation(
Sure I can split it further, but the functionality here hasn't inflated at all, it doesn't do anything it didn't do before.

But I would want to split it into: 
- `getMetricAssignmentRecommendation(experiment, metric, analysis)`
- `getAggregateMetricAssignmentRecommendation(metricAssignmentRecommendations)`

2021-06-29 05:05 UTC, yanirs commented on src/lib/analyses.ts
>  export function getAggregateRecommendation(
Yeah, this split would work too. :slightly_smiling_face:

2021-06-29 05:06 UTC, yanirs commented on src/components/experiments/single-view/results/__snapshots__/ExperimentDebug.test.tsx.snap
> +                      Deploy either variation
Yeah, I figured this is what happened. It'd be nice to make them consistent if it's not too much effort.

2021-06-29 09:04 UTC, jessie-ross commented on src/lib/analyses.ts
>  export function getAggregateRecommendation(
This has ended up being quite a large change, especially with testing changes, should I split it into another PR on top?

2021-06-29 22:38 UTC, yanirs commented on src/lib/analyses.ts
>  export function getAggregateRecommendation(
Yeah, if you think it'd help. I don't mind looking at it as a separate commit in this PR if it's too much effort to split.

2021-07-01 06:45 UTC, yanirs commented on src/lib/analyses.ts
>  export interface AggregateRecommendation {
Should we just call them `Recommendation` and `RecommendationDecision` now? They're not really aggregates.

2021-07-01 08:01 UTC, jessie-ross commented on src/lib/analyses.ts
>  export interface AggregateRecommendation {
Yeah, I would like to do so, but I would like to do so in another PR as this one is ballooning.

Just working on the documentation now.

2021-07-01 13:55 UTC, jessie-ross commented on src/lib/analyses.ts
> +export enum PracticalStatisticalDifferenceStatus {
There are probably still typos but I have added a top-level comment 😄

2021-07-02 01:47 UTC, jessie-ross commented on src/components/experiments/single-view/results/__snapshots__/ExperimentDebug.test.tsx.snap
> +                      Deploy either variation
I have marked `recommendation` as deprecated, so I don't think there is a need to make them consistent now.
Eventually we can actually remove all references to recommendation while still letting the API add recommendation in.

2021-07-02 01:48 UTC, jessie-ross commented on src/components/experiments/single-view/results/__snapshots__/ExperimentDebug.test.tsx.snap
> +                      Deploy either variation
It is currently only used in the Debug view

2021-07-02 01:57 UTC, yanirs commented on src/components/experiments/single-view/results/__snapshots__/ExperimentDebug.test.tsx.snap
> +                      Deploy either variation
Yeah, we can probably retire the Debug tab now that we have the strategy selector and observed data in the main view, especially once #554 is fixed.

2021-07-02 02:30 UTC, yanirs approved these changes
:ship: with just a tiny bit of inline nitpicking :smile: 

The overall documentation can probably be improved a bit, but it's not critical and I may play with it after the stack is merged.

2021-07-02 02:30 UTC, yanirs commented on src/lib/analyses.ts
> +    analysis && metricAssignment && getDiffCredibleIntervalStats(analysis, metricAssignment)
There shouldn't be a need to check the `analysis` again, and we should be able to assume that the metric assignment exists.

Also, `getDiffCredibleIntervalStats()` can handle a null `analysis` and line 177 assumes a non-null/undefined `analysis`.

```suggestion
  const metricAssignment = experiment.metricAssignments.find(
    (metricAssignment) => metricAssignment.metricAssignmentId === analysis.metricAssignmentId,
  ) as MetricAssignment
  const diffCredibleIntervalStats = getDiffCredibleIntervalStats(analysis, metricAssignment)
```

2021-07-02 02:30 UTC, yanirs commented on src/lib/analyses.ts
> +      isPositive === metric.higherIsBetter ? nonDefaultVariation.variationId : defaultVariation.variationId
Just a couple of other ways. Not fussed about this. :slightly_smiling_face: 

No need to go through the variations if we don't use the result:
```suggestion
  let chosenVariationId = undefined
  if (decision === AggregateRecommendationDecision.DeployChosenVariation) {
    const defaultVariation = experiment.variations.find((variation) => variation.isDefault) as Variation
    const nonDefaultVariation = experiment.variations.find((variation) => !variation.isDefault) as Variation
    chosenVariationId =
      isPositive === metric.higherIsBetter ? nonDefaultVariation.variationId : defaultVariation.variationId
```

And we don't need to iterate twice:
```suggestion
  let chosenVariationId = undefined
  if (decision === AggregateRecommendationDecision.DeployChosenVariation) {
    const chooseDefaultVariation = isPositive !== metric.higherIsBetter
    const chosenVariation = experiment.variations.find((variation) => variation.isDefault === chooseDefaultVariation) as Variation
    chosenVariationId = chosenVariation.variationId
```

2021-07-02 02:30 UTC, yanirs commented on src/lib/analyses.ts
> +    // See Kruschke's Precision as a goal for data collection: https://www.youtube.com/playlist?list=PL_mlm7M63Y7j641Y7QJG3TfSxeZMGOsQ4
Can drop this now that it's in the top-level comment.

```suggestion
```

2021-07-02 02:30 UTC, yanirs commented on src/lib/analyses.ts
> + * - More accurate burden of proof - tailored to the Experimenters specific decision they are making.
```suggestion
 * - More accurate burden of proof - tailored to the experimenters' decisions around specific metrics.
```

2021-07-02 02:50 UTC, jessie-ross commented on src/lib/analyses.ts
> +    // See Kruschke's Precision as a goal for data collection: https://www.youtube.com/playlist?list=PL_mlm7M63Y7j641Y7QJG3TfSxeZMGOsQ4
It isn't top level of this file once the recommendation code is moved out.

2021-07-02 03:08 UTC, jessie-ross commented
👍 I am going to merge this one and address these with a PR on top of the stack

2021-07-02 03:11 UTC, merged

2021-07-02 04:15 UTC, jessie-ross commented on src/lib/analyses.ts
> +    analysis && metricAssignment && getDiffCredibleIntervalStats(analysis, metricAssignment)
I will remove the analysis, but there I think it is worth keeping the metricAssignment check - there have been backend/etl bugs before causing the front-end to crash.

2021-07-02 04:20 UTC, jessie-ross commented on src/lib/analyses.ts
> +      isPositive === metric.higherIsBetter ? nonDefaultVariation.variationId : defaultVariation.variationId
I would actually like to rename `chosenVariationId` to be something like `preferredVariationId` or `betterVariationId` and include it when statistically significant, this would allow us to have better health monitoring. We might also want to trigger manual analysis required for cases where there are conflicts of statistical significance, this would be a step in-between what we currently have of conflicting practical significance and what we had before - conflicting practical significance including not practical significant.