Add bookmarklet support for the test user parameter
Automattic/abacus pull request #589
Opened 2021-08-04 04:07 UTC by yanirs

As part of the work on 649-gh-Automattic/experimentation-platform, prompt for and pass in the `test_username` parameter in bookmarklet calls and change the messaging accordingly.

## How has this been tested?

- Automated tests that cover added/changed functionality
- Additional manual testing instructions (please specify): See backend diff (D65112-code)

2021-08-04 07:55 UTC, jessie-ross requested changes
Left some minor code/clarity comments.

Looking at it now, manual assignment is feeling a bit overloaded and magical.

I think what might help is manual assignment is expanding the tooltip or [opening up a modal instead](https://material-ui.com/components/modal/) which explains the new manual assignment, and providing separate links for different types of assignment - and within those different links adding more detailed error checking.

At the very least I think we need to expand on the instructions in the tooltip.

2021-08-04 07:55 UTC, jessie-ross commented on src/components/experiments/single-view/overview/VariationsTable.tsx
> +       testUsername = prompt(
Can we rename testUsername to something else?

2021-08-04 07:55 UTC, jessie-ross commented on src/components/experiments/single-view/overview/VariationsTable.tsx
> +         '(1) Enter a test username to assign (only works for staging experiments).\\n' +
```suggestion
         '(1) Enter a username to assign (only works for staging experiments).\\n' +
```

2021-08-04 07:55 UTC, jessie-ross commented on src/components/experiments/single-view/overview/VariationsTable.tsx
> +          'To assign yourself or a test user, you must run this from Abacus and specify an existing user.\\n\\n' +
```suggestion
          'To assign yourself or a specified user, you must run this from Abacus and specify an existing user.\\n\\n' +
```

2021-08-05 02:22 UTC, yanirs commented on src/components/experiments/single-view/overview/VariationsTable.tsx
> +       testUsername = prompt(
I'm not too fussed. Do you have any suggestions?

2021-08-05 02:23 UTC, yanirs commented on src/components/experiments/single-view/overview/VariationsTable.tsx
> +         '(1) Enter a test username to assign (only works for staging experiments).\\n' +
I was trying to emphasise that it shouldn't be a real user, but I don't mind going with this suggestion.

2021-08-05 02:45 UTC, yanirs commented
> Left some minor code/clarity comments.
> 
> Looking at it now, manual assignment is feeling a bit overloaded and magical.
> 
> I think what might help is manual assignment is expanding the tooltip or [opening up a modal instead](https://material-ui.com/components/modal/) which explains the new manual assignment, and providing separate links for different types of assignment - and within those different links adding more detailed error checking.
> 
> At the very least I think we need to expand on the instructions in the tooltip.

Thanks @jessie-ross! I expanded the tooltip instructions in https://github.com/Automattic/abacus/pull/589/commits/1389afce333e62cacab58d0e748d61ec54d389b9.

I agree that it is a bit too magical. I believe that the original thinking was to make it easy to switch variations while testing a specific page, but things are different now that we rely a lot on Abacus authentication. It may be better to completely remove the bookmarklet in favour of a dialogue where users can specify a named user or an anonymous user ID. We'd just have to make it a bit easier to grab the anon ID. What do you think? I can open an issue and we can address it separately.

2021-08-05 04:29 UTC, jessie-ross commented on src/components/experiments/single-view/overview/VariationsTable.tsx
> +       testUsername = prompt(
`username_override`?

2021-08-05 04:32 UTC, jessie-ross commented
> It may be better to completely remove the bookmarklet in favour of a dialogue where users can specify a named user or an anonymous user ID. We'd just have to make it a bit easier to grab the anon ID. What do you think? I can open an issue and we can address it separately.

Yeah! Sounds like a good idea that we can look into at a later time.

2021-08-05 04:40 UTC, jessie-ross commented on src/components/experiments/single-view/overview/VariationsTable.tsx
>                          </ol>
Hmm, how about splitting this over two separate headers: 'Logged-in Assignment Instructions' and 'Logged-out Assignment Instructions'?

- I think we should also specify the need to be proxied/authorised.
- Also we could add "check that tracks is enabled and running" (a lot of us run ad-blockers).

2021-08-05 08:08 UTC, yanirs commented on src/components/experiments/single-view/overview/VariationsTable.tsx
>                          </ol>
Good ideas!

2021-08-05 08:22 UTC, yanirs commented
> Yeah! Sounds like a good idea that we can look into at a later time.

Opened #590 and addressed the other comments in 1f992b35a4928d8091a01b6d839114193449421b.

2021-08-05 08:29 UTC, jessie-ross approved these changes
<img width="520" alt="Screen Shot 2021-08-05 at 4 28 18 pm" src="https://user-images.githubusercontent.com/971886/128318266-4893b6e7-8001-4c07-9cd6-93146c3487ec.png">

Looking good!

2021-08-06 06:01 UTC, merged