Change font styles for metric assignment results based on significance.
Automattic/abacus pull request #600
Opened 2021-10-03 22:05 UTC by is4ac

This PR emphasizes significant results and de-emphasizes insignificant ones in the Metric Assignment Results table.

- Bold font == practically and statistically significant
- Light grey font == practically insignificant and/or statistically insignificant
- The light grey is the same as the Health Report table grey
- Also added an info icon with a tooltip explaining the meaning of the style differences

ActualExperimentResults.tsx was edited to add the varying font styles based on if the results were practically significant and statistically significant.

In issue #555, it was mentioned that:

> We could then add an info icon somewhere in the header educating experimenters about these three styles.

Is the info icon with tooltip a good implementation of this, or is there a better way to design this?

Before
<img width="1320" alt="Screen Shot 2021-10-03 at 4 58 37 PM" src="https://user-images.githubusercontent.com/1518252/135772832-c9fde474-523b-4231-9c68-f9bc844692db.png">

After
<img width="1316" alt="Screen Shot 2021-10-03 at 4 38 50 PM" src="https://user-images.githubusercontent.com/1518252/135772706-033aa94b-037e-4595-87f4-4ad5018be6d5.png">

Closes #555 

## How has this been tested?

- Automated tests that cover added/changed functionality
- Manual testing with production data (locally)
- Updated snapshot for testing this change

2021-10-04 07:35 UTC, jessie-ross requested changes
Hmm, yeah this is a bit tricky.

I think it would help to go back to the purpose of this change, which is to make a long list of metric assignments a bit more readable. Now that I am looking at an example design, I can see some potential issues with the overall idea:
- "Deploy either variation" is an important and significant result, which we don't want to get buried.
- Inconclusive can be important too - it could hide a potentially large uncertainty to hide these.

I am a bit on the fence about adding this feature but, maybe a toned down version where we just bold the recommendation when it is a deploy recommendation would work. What do you think?

(Also leaving some inline comments for learning.)

2021-10-04 07:36 UTC, jessie-ross commented on src/components/experiments/single-view/results/ActualExperimentResults.tsx
> +            </Tooltip>
I think if we need to explain the design we are going in the wrong direction.

2021-10-04 07:39 UTC, jessie-ross commented on src/components/experiments/single-view/results/ActualExperimentResults.tsx
> +    typeof recommendation.statisticallySignificant !== 'undefined' &&
I think these should never be undefined, if you are using VSCode / another editor with a TS language server, it should let you know.

2021-10-04 07:42 UTC, jessie-ross commented on src/components/experiments/single-view/results/ActualExperimentResults.tsx
> +    recommendation.statisticallySignificant
Practically significant implies statistical significance 😉

2021-10-04 07:44 UTC, jessie-ross commented on src/components/experiments/single-view/results/ActualExperimentResults.tsx
> +    [`significanceStatus${Recommendations.PracticalSignificanceStatus.Yes}`]: {
If we were going round this path we could use a single class "isSignificant", with no need for dynamic class names.

2021-10-04 07:45 UTC, jessie-ross commented on src/components/experiments/single-view/results/ActualExperimentResults.tsx
> +            <MetricValueInterval
With custom components like this and `RecommendationDisplay`, we should add `className` properties, instead of wrapping in a div.

2021-10-06 00:41 UTC, is4ac commented
> Hmm, yeah this is a bit tricky.
> 
> I think it would help to go back to the purpose of this change, which is to make a long list of metric assignments a bit more readable. Now that I am looking at an example design, I can see some potential issues with the overall idea:
> 
> * "Deploy either variation" is an important and significant result, which we don't want to get buried.
> * Inconclusive can be important too - it could hide a potentially large uncertainty to hide these.
> 
> I am a bit on the fence about adding this feature but, maybe a toned down version where we just bold the recommendation when it is a deploy recommendation would work. What do you think?

I agree that it might be a bit much to de-emphasize "insignificant" results, especially if they might contain valuable lessons for the experimenter. Bolding could work, but that still makes it hard to distinguish between different kinds of significant outcomes. 

What if we had color coded icons next to each type of recommendation? That way, it doesn't necessarily imply to the user that they should ignore certain results, but it would still allow for quick visual processing. For example, one idea could be:

- A green check mark for "Deploy treatment" or "Deploy either variation"
- A yellow sign (warning symbol?) for "Deploy control" or "Inconclusive"
- A red X for "Missing analysis" or "Manual analysis required"

I'm not exactly sure what the best way to color code the various results would be.. Thoughts?

2021-10-06 00:42 UTC, is4ac commented on src/components/experiments/single-view/results/ActualExperimentResults.tsx
> +            </Tooltip>
I don't think that's always true of designs in general (especially if it's a totally new interface), but in this case, I agree that it should be something that intuitively makes sense to people.

2021-10-06 00:45 UTC, is4ac commented on src/components/experiments/single-view/results/ActualExperimentResults.tsx
> +    typeof recommendation.statisticallySignificant !== 'undefined' &&
Gotcha, in the interface definition it has those two variables with a ? at the end, so I assumed it was possible that they could be undefined.

2021-10-06 00:46 UTC, is4ac commented on src/components/experiments/single-view/results/ActualExperimentResults.tsx
> +    recommendation.statisticallySignificant
Ooh, right, good point! 😁 Still learning! 😊

2021-10-06 05:08 UTC, jessie-ross commented on src/components/experiments/single-view/results/ActualExperimentResults.tsx
> +    typeof recommendation.statisticallySignificant !== 'undefined' &&
Oh, I think I was looking at the wrong place.

2021-10-06 05:20 UTC, jessie-ross commented
> What if we had color coded icons next to each type of recommendation? That way, it doesn't necessarily imply to the user that they should ignore certain results, but it would still allow for quick visual processing. For example, one idea could be:

Hmm I feel these could clutter the page a bit, and I don't think we should be associating some of these states as good/bad/warning as they may not mean that.

> Or we could make it match the Health Report table and change the background color of the Recommendation cells in the Metric Assignment Results table?

Yeah this is similar design wise as the current plan, just a different way to emphasise and de-emphasise, but linking it more to the categorical good/bad/warning.

---

I think we need to look at from a high level and decide:
- What states do we want to emphasise (why do we want to emphasise some states).
- What states do we want to de-emphasise (why do we want to de-emphasise some states).
- If we need to, is there a way to emphasise some rows without de-emphasising other rows.

2021-11-23 01:15 UTC, aaronyan commented
Where did y'all land in your 1:1 discussion around this?

2021-11-23 14:48 UTC, is4ac commented
> Where did y'all land in your 1:1 discussion around this?

@jessie-ross can correct me if I'm wrong, but I think we settled on tabling the issue until we could have a big picture discussion on what we want to actually emphasize or de-emphasize in the table. We thought it was low priority enough at the time that we didn't continue the discussion in favor of focusing on other things.

2022-01-21 22:12 UTC, is4ac commented
Closing in favor of (690-gh-Automattic/experimentation-platform)

2022-01-21 22:12 UTC, closed without merging