Add a RowToggleButton component for use in AG Grid master/detail component
Automattic/abacus pull request #622
Opened 2021-12-22 02:49 UTC by is4ac

## Changes in this PR

This PR adds a `RowToggleButton` component for use in the AG Grid master/detail component that will be added in a later PR. This is part of addressing #604 in converting the Metrics table to use AG Grid.

**Note:** This PR does not actually use the `RowToggleButton` component anywhere yet. It just includes the component code and tests. A future PR for the AG Grid master/detail component will make use of this component.

## How has this been tested?

- Automated tests that cover added/changed functionality
- Manual testing with production data (locally)
- Manual testing with mock data (locally or on Vercel)

2022-01-11 04:15 UTC, jessie-ross requested changes

2022-01-11 04:15 UTC, jessie-ross commented on src/components/general/RowToggleButton.tsx
> +  }, [isToggled, classes.rotated, classes.notRotated])
There is no need to have cls as state, it should be a value directly derived from toggled.

2022-01-11 04:15 UTC, jessie-ross commented on src/components/general/RowToggleButton.tsx
> +  }, [toggled])
It is an anti-pattern to be caching state within a component, [we should be lifting this state up and out of here](https://reactjs.org/docs/lifting-state-up.html#lessons-learned).

This component shouldn't have any state and shouldn't need any effects, it should simply have params: `isOpen`, and `onClick`.

2022-01-11 04:15 UTC, jessie-ross commented on src/components/general/RowToggleButton.tsx
> +const RowToggleButton = ({
Let's decouple the naming from the use-case, how about `ChevronToggleButton`

2022-01-11 04:15 UTC, jessie-ross commented on src/components/general/RowToggleButton.tsx
> +    setIsToggled(!isToggled)
Case in point: What if the outer component wants to modify the logic that occurs on click, maybe have loading state, maybe disable state, etc.

2022-01-11 17:18 UTC, is4ac commented on src/components/general/RowToggleButton.tsx
> +  }, [toggled])
Thanks, that makes sense. I think I ended up with this design because there were some complications with how AG Grid renders (or doesn't re-render) cell renderers. I'll do some more digging to fix that pattern!

2022-01-11 17:19 UTC, is4ac commented on src/components/general/RowToggleButton.tsx
> +const RowToggleButton = ({
I like that idea!

2022-01-11 23:47 UTC, is4ac commented on src/components/general/RowToggleButton.tsx
> +const RowToggleButton = ({
Actually, I just realized I wanted to make it possible to customize the icon. What about `IconToggleButton`?

2022-01-14 08:43 UTC, jessie-ross commented on src/components/general/RowToggleButton.tsx
> +const RowToggleButton = ({
Rotating sounds good, but I am not sure when this would be used? Do you have a use case?

2022-01-14 15:09 UTC, is4ac commented on src/components/general/RowToggleButton.tsx
> +const RowToggleButton = ({
> I am not sure when this would be used? Do you have a use case?

Do you mean besides where it's being used in AgGridWithDetails? I guess it could be used in other custom components that need a button to indicate expansion. If you don't think this needs to be a separate file, it could easily be added to the AgGridWithDetails.utils file.

2022-01-14 15:52 UTC, jessie-ross commented on src/components/general/RowToggleButton.tsx
> +const RowToggleButton = ({
As in where we would use a custom icon for this component?

2022-01-14 16:28 UTC, is4ac commented on src/components/general/RowToggleButton.tsx
> +const RowToggleButton = ({
> As in where we would use a custom icon for this component?

Oh, I see! I guess I was just thinking if a designer ever wanted to create custom icons in the future, it would be easy to swap out, for not much engineering effort. If you don't think it's necessary I could definitely take out that part.

2022-01-17 04:52 UTC, jessie-ross commented on src/components/general/RowToggleButton.tsx
> +const RowToggleButton = ({
Yeah, I think this is a case of YAGNI and it might be a good design constraint to ensure all open/close buttons are consistent.

2022-01-17 15:22 UTC, is4ac commented
Renamed to `ChevronToggleButton` and got rid of the custom icon option. Let me know how it looks now!

2022-01-18 03:22 UTC, jessie-ross approved these changes
Just a couple of last changes, but other than that it is good to go.

2022-01-18 03:22 UTC, jessie-ross commented on src/components/general/ChevronToggleButton.tsx
> +  const handleClick = () => {
Let's also make `onClick` required so we don't need this function.

2022-01-18 03:22 UTC, jessie-ross commented on src/components/general/ChevronToggleButton.tsx
> +  icon?: JSX.Element
I think this was left in by accident.

2022-01-18 03:22 UTC, jessie-ross commented on src/components/general/ChevronToggleButton.test.tsx
> +test('button rotates depending on isOpen prop', async () => {
Let's go ahead with this PR, but a note for the future: Since ChevronToggleButton is so small and simple I would include it in the next PR, and not write any unit tests specifically for it - it will be covered by where it is used.

2022-01-19 00:29 UTC, merged