Add AG Grid component with master/detail feature
Automattic/abacus pull request #623
Opened 2021-12-22 03:06 UTC by is4ac

## Changes in this PR

Adds a generic `AgGridWithDetails` component that can render any data table with a master/detail toggle feature. This component will be used to help convert the Metrics table to use AG Grid in a future PR. This is another step in addressing #604.

**Note:** This component is not actually being rendered anywhere in this branch. This PR just adds the component code and unit tests for future use.

## How has this been tested?

- Automated tests that cover added/changed functionality
- **Note:** the jest code coverage isn't 100% so it fails in this branch. However, the next PR that actually converts the Metrics table to use this component adds tests that cover the rest.

2022-01-11 09:16 UTC, jessie-ross requested changes
I have only given this a first pass so far, I think this code should be drastically simplified and the PR focused solely on the master/detail component.

2022-01-11 09:16 UTC, jessie-ross commented on src/components/general/AgGridWithDetails.utils.tsx
> +  if (!isFullWidth(event.data) && getDataId && gridApiRef) {
How about using early returns here to simplify the code and reduce the need for nested if statements.

2022-01-11 09:16 UTC, jessie-ross commented on src/components/general/AgGridWithDetails.tsx
> +  const detailRowToggleMap = useRef<Map<string, boolean>>(new Map())
Is there a reason to use Map types instead of ordinary objects?

2022-01-11 09:16 UTC, jessie-ross commented on src/components/general/AgGridWithDetails.utils.tsx
> +export const isDataArray = (data: unknown[]): data is Data[] => {
I don't understand the need for the separate type and hence this type-guard?

2022-01-11 09:16 UTC, jessie-ross commented on src/components/general/AgGridWithDetails.utils.tsx
> +  detailRowToggleMap.set(getDataId(data), !detailRowExists)
I'm not happy with this occurring as a side-effect

2022-01-11 09:16 UTC, jessie-ross commented on src/components/general/AgGridWithDetails.utils.tsx
> +    newRows = addDetailRow(data, rowData, getDataId)
I don't see the need to modify the rows to add and remove detail rows.

Why don't we have a `rowsWithDetailRows` constant that is derived from `rowData` and `detailRowToggleMap`?

2022-01-11 09:17 UTC, jessie-ross commented on src/components/general/AgGridWithDetails.tsx
> +const AgGridWithDetails = ({
With the other components in a separate later PR

2022-01-11 17:20 UTC, is4ac commented on src/components/general/AgGridWithDetails.test.tsx
> +  await waitForSeconds(0.5)
Oh yes, this must be an artifact from when I was first debugging the tests. I eventually got the jest timer mocks to work, but I must have missed this one. Thanks!

2022-01-11 17:22 UTC, is4ac commented on src/components/general/AgGridWithDetails.tsx
> +// istanbul ignore file; demo
Oh no, I don't think so. Looking back, I think this was an artifact from copying the ExperimentsTableAgGrid. Looks like that file also has an `istanbul ignore file` which should probably be removed.

2022-01-11 17:26 UTC, is4ac commented on src/components/general/AgGridWithDetails.utils.tsx
> +  const dataId = useRef<string>('')
To be honest, I don't remember exactly either.. 😅 I think I was debugging something with the row toggle button and re-rendering and forgot to change this back. Good catch!

2022-01-11 17:27 UTC, is4ac commented on src/components/general/AgGridWithDetails.utils.tsx
> +    newRows = addDetailRow(data, rowData, getDataId)
That's a great idea!

2022-01-11 17:28 UTC, is4ac commented on src/components/general/AgGridWithDetails.utils.tsx
> +export const isDataArray = (data: unknown[]): data is Data[] => {
To be honest, I am still fairly new to TypeScript, so I wasn't sure of the best way to handle this when I first started coding this. I can get rid of this unnecessary step and figure out a better way to type it!

2022-01-11 17:30 UTC, is4ac commented on src/components/general/AgGridWithDetails.tsx
> +  const detailRowToggleMap = useRef<Map<string, boolean>>(new Map())
Not to my knowledge, no. I was just more familiar with the concept of a map being called Map. If there's no downside in this case to using an ordinary object as a map, then I can make that switch!

2022-01-11 17:33 UTC, is4ac commented on src/components/general/AgGridWithDetails.tsx
> +  }, [data])
IIRC, I think this was also a side effect of me not understanding TypeScript very well (the roundabout type checking going on). I should be able to get rid of this.

2022-01-14 11:01 UTC, jessie-ross requested changes
I've given this a deeper look-over, I haven't yet looked at the row-height functionality or testing.

2022-01-14 15:13 UTC, is4ac commented on src/components/general/AgGridWithDetails.tsx
> +    getRowNodeId,
It is actually extended inline on line 134:

```TypeScript
getRowNodeId={(data: Record<string, unknown>) => {
  return isFullWidth(data) ? detailIdFromDataId(getRowNodeId(data)) : getRowNodeId(data)
}}
```

2022-01-14 15:13 UTC, is4ac commented on src/components/general/AgGridWithDetails.tsx
> +  const maxRowHeightMap = useRef<Record<string, number>>({})
Oh, yeah that makes sense. Will do!

2022-01-14 15:15 UTC, is4ac commented on src/components/general/AgGridWithDetails.tsx
> +  }
Yeah, you're right. I originally had other helper functions that was using this function, but it's been refactored enough that it's no longer that useful. I can get rid of it.

2022-01-14 15:22 UTC, is4ac commented on src/components/general/AgGridWithDetails.utils.tsx
> +}
A reduction sounds good to me!

2022-01-14 15:23 UTC, is4ac commented on src/components/general/AgGridWithDetails.tsx
> +      : {}),
Oh yeah, I could probably replace this with `defaultColDef: defaultColDef || {}` or something similar.

2022-01-14 15:27 UTC, is4ac commented on src/components/general/AgGridWithDetails.utils.tsx
> +export const isFullWidth = (data: Record<string, unknown> & { isDetail?: boolean }): boolean => data.isDetail === true
I was using the terminology used by AG Grid, but a better name would probably be `isDetailRow`. Hmm, I guess it's debatable as to which is more readable: `isDetailRow(data)` or `data.isDetail`. I don't feel too strongly either way, but it might make typing trickier if we go with your suggestion of stricter typing, since many times the `data` variable is coming directly from the AG Grid API.

2022-01-14 15:31 UTC, is4ac commented on src/components/general/AgGridWithDetails.utils.tsx
> +  if (actionColumnIdSuffix && event.column.getColId().endsWith(actionColumnIdSuffix)) {
> Oh I see, we detect a whole row click.
> 
> I am not a fan of this method as wherever we use this component we have to whitelist which columns we want to have actions. I think there should be a simpler way to do this - like check if we are providing html components or a custom cell renderer? How does the previous material grid do so?

I'm not so sure that there is a simpler method, at least not an automatic method that I can think of off the top of my head. The previous material grid also had master detail row functionality so it handled things like this without any additional coding.

The problem with checking for HTML components or custom cell renderers is that not all custom cell renderers are action columns. For example, in the Metrics table, the "Name" column is a custom cell renderer that adds a hover `Tooltip` but there is no action.

2022-01-14 15:36 UTC, is4ac commented on src/components/general/AgGridWithDetails.utils.tsx
> +  if (target && (target === element || element?.contains(target))) {
Oh, now that the method of adding/removing detail rows has changed, I think this could be simplified. I'll have to test it out, but I don't think there needs to be a separate if/else now. Sorry, this was a vestige of debugging the previous version before I implemented changes.

2022-01-14 15:40 UTC, is4ac commented on src/components/general/AgGridWithDetails.utils.tsx
> +export const getRowHeight = (
Technically, it is general because [returning `null`/`undefined` results in using the default/auto row height](https://www.ag-grid.com/react-data-grid/row-height/#reference-styling-getRowHeight). But I decided to take out the conditional while addressing your other comment and move it to the inline definition in the other file because I think that does make it simpler.

2022-01-14 15:57 UTC, jessie-ross commented on src/components/general/AgGridWithDetails.utils.tsx
> +  if (actionColumnIdSuffix && event.column.getColId().endsWith(actionColumnIdSuffix)) {
An example of this is if we swap out the Experiments list table, we wouldn't be able to click on the experiment name and go to the experiment, we would have to whitelist that column.

I think we should be able to do this by inspecting the event target and seeing if the target is the AgGrid Cell.

2022-01-14 16:15 UTC, is4ac commented on src/components/general/AgGridWithDetails.utils.tsx
> +  if (actionColumnIdSuffix && event.column.getColId().endsWith(actionColumnIdSuffix)) {
> I think we should be able to do this by inspecting the event target and seeing if the target is the AgGrid Cell.

But then you would no longer be able to click on anywhere on the row to open the detail row, which was possible with the material table. Or do you mean something else by this?

2022-01-14 16:18 UTC, is4ac commented on src/components/general/AgGridWithDetails.utils.tsx
> +export const isFullWidth = (data: Record<string, unknown> & { isDetail?: boolean }): boolean => data.isDetail === true
> I think we need to use symbols or prefixes for isDetail and isOpen (e.g. AgGridWithDetails-isDetail) so they can never clash with normal row columns.

This is a good point!

2022-01-14 16:23 UTC, is4ac commented on src/components/general/AgGridWithDetails.utils.tsx
> +  if (actionColumnIdSuffix && event.column.getColId().endsWith(actionColumnIdSuffix)) {
I can play around with some other ideas to see if I can get it to work, but I'm not sure checking the event target will work. As an example, the current Metrics table wouldn't allow for clicking on the metric name to toggle the detail row, even though clicking on the name itself doesn't do anything else.

2022-04-19 04:09 UTC, closed without merging