Retain grid history: Save last search, sort, and filter state as URL params
Automattic/abacus pull request #635
Opened 2022-01-05 18:18 UTC by is4ac

**Stacked PR 2/2 for retaining search history:** based on #634.

Saves the search string as a URL param, e.g. `/experiments?search=explat_test` so that the last search filter is retained. Allows the back button to work properly on Abacus.

This series of stacked PRs closes #545.

## How has this been tested?

- Automated tests that cover added/changed functionality
- Manual testing with production data (locally)
- Manual testing with mock data (locally or on Vercel)

2022-01-06 19:44 UTC, aaronyan commented
Tested the save last search string, and it works well for me!

2022-01-14 16:16 UTC, jessie-ross requested changes
- I think we should be looking at url state on the page level from the `/pages` component, passing page parameters up and down. I think we should be able to avoid the state caching in the middle.
- We need to cleanly abstract the parameters and url code from the rest of the code - lets have `pageParams`, `setPageParams` and maybe `replacePageParams` (to indicate a history replacement) abstracting it away.
- We need a way to "type" pageParams depending on the page.
- The other side of this is we want to abstract the certain values out of the grid, we want to be able to pass in `gridState` and `setGridState`.
- We also want this to be decoupled from any particular grid so we can apply it to Metrics table as well.

2022-01-14 16:33 UTC, is4ac commented
Those are all great ideas! Thanks for the direction.

> * We need a way to "type" pageParams depending on the page.

I was having difficulty with this one. I was originally trying to [use template string pattern index signatures](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#symbol-and-template-string-pattern-index-signatures) to do this properly, but the project's version of TypeScript needs to be updated, and I wasn't sure how to update it and get it to work with CRA. Any ideas or help on this one would be appreciated.

2022-01-20 14:53 UTC, is4ac commented
Still a work in progress, but I've tried abstracting the parts you mentioned into 2 custom hooks: `useGridState` to manage the grid search, sort, and filter states, and a `usePageParams` that manages the URL params and history manipulation. The functionality works well so far, and I think it's made the code a lot cleaner and more reusable, but I'm still working on commenting and polishing it up. 

@jessie-ross what do you think of the direction so far?

Also: I might just end up merging the remaining 3 PRs into one PR since they are all related features. This version has the full functionality of saving the search, sort, and filter states.

2022-01-21 11:38 UTC, jessie-ross commented on src/utils/url-params.ts
> +export const usePageParams = (initialParams?: UrlParams): UsePageParamsProps => {
I would use a typescript generic for `UrlParams` and perhaps we should pass in a schema to validate the params.

2022-01-21 11:38 UTC, jessie-ross commented on src/utils/url-params.ts
> +export const usePageParams = (initialParams?: UrlParams): UsePageParamsProps => {
Naming: UrlParams vs ParamsObj vs PageParams - we should stick to one

2022-01-21 11:38 UTC, jessie-ross commented on src/utils/url-params.ts
> +export const getParamsStringFromObj = (paramsObj: UrlParams): string => {
`FromObj` is a bit lazy, lets write full names

2022-01-21 11:38 UTC, jessie-ross commented on src/utils/url-params.ts
> +  const [pageParams, setPageParams] = useState<UrlParams>(params)
I think we should be able to avoid cached state in here by using and updating the URL state directly along with default state if anything isn't set.

2022-01-21 11:38 UTC, jessie-ross commented on src/utils/url-params.ts
> +export const usePageParams = (initialParams?: UrlParams): UsePageParamsProps => {
`initialState` should instead be `defaultState`.

2022-01-21 11:38 UTC, jessie-ross commented on src/utils/url-params.ts
> +    setPageParams,
You should draw a diagram to understand the way state updates, ideally everything should flow down.

If we give out export state we need to update state upwards and have to keep state in two places (here and in the url) in sync.

2022-01-21 11:51 UTC, jessie-ross commented on src/utils/ag-grid.test.tsx
> +import { render } from '@testing-library/react'
In general I would avoid writing tests until you know what the solution is going to look like.

2022-01-21 11:51 UTC, jessie-ross commented on src/utils/ag-grid.ts
> +  const initialState = initialGridState || {
We should have grid state just be an object that describes grid state, we should be able to remove reference management from it.

2022-01-21 11:51 UTC, jessie-ross commented on src/pages/experiments/ExperimentsAgGrid.tsx
> +  const { gridState, updateGridState } = useGridState(defaultGridState)
We shouldn't need grid state stored in this component, we should have a `pageParams -> gridState` function and `gridState -> pageParams` to use in `onGridStateChange((gridState) => pushPageParams(gridStateToPageParam(gridState)))`

2022-01-21 18:46 UTC, is4ac commented on src/utils/url-params.ts
> +    setPageParams,
This was great advice! It helped me solve some frustrating issues with the previous method with infinite loops/race conditions.

2022-01-21 21:49 UTC, is4ac commented on src/utils/url-params.ts
> +export const usePageParams = (initialParams?: UrlParams): UsePageParamsProps => {
How about `UrlSearchParams` to differentiate it from react-router-dom `useParams`? I think UrlParams or PageParams isn't descriptive enough, and ["search" params matches the standard query string terminology](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams).

2022-01-21 21:59 UTC, is4ac commented on src/pages/experiments/ExperimentsAgGrid.tsx
> +  const { gridState, updateGridState } = useGridState(defaultGridState)
Currently, I can't get the Reset button to work without using a ref because resetting multiple parts of the grid state at once (search text, sort, filter) causes `onGridStateChange` to trigger multiple times and causes a race condition.

So does having a `gridStateRef` in this component acceptable?

2022-01-21 22:08 UTC, is4ac commented
Addressed everything except for the typing and schema validation because I wasn't very confident on how to do that yet. I hope how it's set up currently makes it not too difficult to add.

2022-04-19 04:09 UTC, closed without merging