Update deployment recommendations
Automattic/abacus pull request #674
Opened 2022-04-08 15:33 UTC by razvanpapadopol

## How has this been tested?

- Automated tests that cover added/changed functionality
- Manual testing with production data (locally)
- Manual testing with mock data (locally or on Vercel)
- Additional manual testing instructions (please specify):

2022-04-08 15:58 UTC, razvanpapadopol commented on src/lib/recommendations.ts
> +  const kruschkeUncertainty = diffCiWidth / ropeWidth
Recently removed in https://github.com/Automattic/abacus/pull/656/files#diff-ba214e0955161d45439a1273a5d1ba03d9883ae978745631a960c046291959dd

2022-04-10 03:15 UTC, jessie-ross requested changes
Thanks for the all the cleanup here! I've added some structuring suggestions - the main part is merging decision and deployRecommendation together.

2022-04-10 03:15 UTC, jessie-ross commented on src/lib/recommendations.ts
> +      if (kruschkeUncertainty < 0.8 && runtimeInDays > 7) return DeploymentRecommendations.DeployCautiously
Let's make these numbers constants e.g. "maxSafeKruschke" and "minSafeRuntime".

7 day runtime can be an issue for some experiments - e.g. email and pipe.
I think we should whitelist some platforms where we don't perform the check.

`kruschkeUncertainty < 0.8` is far too low IMO, this is what we had before and was almost always triggering a warning - resulting in experimenters ignoring it. `1.5` or `2` might be better.

2022-04-11 14:25 UTC, razvanpapadopol commented on src/lib/recommendations.ts
> +type DeploymentRecommendation = typeof DeploymentRecommendations[DeploymentRecommendationKey]
Removed the intermediary type in c79ab7a02ac438c6cdfe462e8e3b73208ea47fdd
Type union may be a good alternative as well if we don't need an object. I guess we'll experiment with both

2022-04-14 21:23 UTC, aaronyan reviewed
Looking really good so far, @razvanpapadopol! Thanks for cleaning up the decoration styles and adding the new deployment recommendations.

2022-04-14 21:23 UTC, aaronyan commented on src/lib/recommendations.ts
> +      if (kruschkeUncertainty < 0.8 && runtimeInDays > 7) return DeploymentRecommendations.DeployCautiously
> 7 day runtime can be an issue for some experiments - e.g. email and pipe.
I think we should whitelist some platforms where we don't perform the check.

Great idea!

We could also use metric attribution windows to inform when to share deployment recommendations, but maybe save it for another PR.

> resulting in experimenters ignoring it. 1.5 or 2 might be better

I'm cool with relaxing the `kruschkeUncertainty` condition by case:
- `NoDifference`: relax to `0.9` since we know the interval will be between ROPE
- `VariantBarelyAhead`: tighten to `0.45` (0.9/2) since we know the interval will be between 0 and min diff
- `VariantAhead`: expand to `1.5`. If we find this to be too generous, it will be easy to tune down
- `VariantWins`: relax to not require `kruschkeUncertainty` (already implemented)

I like having strict `kruschkeUncertainty` for when we make deployment recommendations. If `kruschkeUncertainty` condition is never satisifed, we may never recommend deploying, which I think is okay. I'm still good with willing to relax the condition though! :)

2022-04-15 13:56 UTC, razvanpapadopol commented on src/lib/experiments.ts
> +export function getChosenVariation(analysis: Recommendation, experiment: ExperimentFull): Variation {
Makes sense! I've applied this bit of feedback directly to the base PR where the function was introduced.

https://github.com/Automattic/abacus/blob/0b1f1b4a047c2e407f7628b398c7a62369dd9e2b/src/components/experiments/single-view/results/AnalysisDisplay.tsx#L19

2022-04-15 17:24 UTC, razvanpapadopol commented on src/lib/recommendations.ts
> +      if (kruschkeUncertainty < 0.8 && runtimeInDays > 7) return DeploymentRecommendations.DeployCautiously
Thanks both for the thoughtful input ❤️ 

> Let's make these numbers constants e.g. "maxSafeKruschke" and "minSafeRuntime".

I've introduced the constants together with a map of different cases for `kruschkeUncertainty` in [a0bc5cb](https://github.com/Automattic/abacus/pull/674/commits/a0bc5cb53813074d646036375c2f1ad9b6ddbfc2)

> Let's make these numbers constants e.g. "maxSafeKruschke" and "minSafeRuntime".
>
> 7 day runtime can be an issue for some experiments - e.g. email and pipe.
> I think we should whitelist some platforms where we don't perform the check.

The platform whitelisting was added in [d04ac59](https://github.com/Automattic/abacus/pull/674/commits/d04ac596e389d5eb7596d9efb8953480918f59a5)

> use metric attribution windows to inform when to share deployment recommendations, but maybe save it for another PR.

Sounds like an interesting tiny feature. Saying something like "3 more days needed for a deployment recommendation" on a tooltip should be more helpful than just `Not enough data [...] at this time`.

2022-04-18 14:10 UTC, razvanpapadopol commented on src/lib/recommendations.ts
> +export function getDeploymentRecommendation(
Thanks for sharing this suggestion, @jessie-ross! I've started to explore this possibility in https://github.com/Automattic/abacus/pull/676 but here are a few concerns from my side:
* Analysis decision and deployment recommendation are separate concepts in this new approach and their values don't have 1:1 correspondence, as [illustrated in the flowchart](https://user-images.githubusercontent.com/4505888/156829388-85625ccc-05c0-45df-984a-aee4f62c5620.png).
* Having two separate functions makes unit testing more accessible and in line with the business logic.

2022-04-18 14:28 UTC, razvanpapadopol commented on src/components/experiments/single-view/results/DeploymentRecommendation.tsx
> +export default function DeploymentRecommendation({
Aside from what I've shared in https://github.com/Automattic/abacus/pull/674#discussion_r852143557, I don't think there is much to be reused here as this React component doesn't really render any markup (except for the Tooltip). However, we can do it by adding a new prop: `variant: 'analysisDecision' | 'deploymentRecommendation'`. Or maybe there is another way I'm missing? 🤔

2022-04-20 15:13 UTC, jessie-ross commented on src/lib/experiments.ts
> +export function getChosenVariation(experiment: ExperimentFull, analysis: Recommendation): Variation {
In this codebase an `analysis` always refers to an `Analysis` object, I think we should rename this variable `recommendation`.

2022-04-20 15:13 UTC, jessie-ross commented on src/lib/recommendations.ts
> +export function getDeploymentRecommendation(
Yeah those are good points.

I think what might work is if we reorient this function - what it is doing is taking a decision and deciding if the data is strong enough - if we isolate and refocus on that aspect we can have a function like: `isDataStrongEnough(analysis, decision, experiment, metricAssignment): boolean`. 

We can add this as an extra dimension Recommendation, and that would remove the duplication of "decision", while retaining the separation and even improving unit-testability. How does that sound?

2022-05-03 17:26 UTC, jessie-ross approved these changes
LGTM with #674!

2022-05-05 20:59 UTC, merged