Fix warnings in unit tests
Automattic/abacus pull request #688
Opened 2022-05-06 07:16 UTC by jessie-ross

**This PR fixes warnings in unit tests.**

- There is one warning left that needs an update of `testing-library` #687

## How has this been tested?

- Automated tests that cover added/changed functionality

2022-05-06 15:27 UTC, razvanpapadopol requested changes
Thanks for fixing these! Left just one tiny note.

2022-05-06 15:27 UTC, razvanpapadopol commented on src/components/experiments/single-view/ExperimentPageView.tsx
> +              <Tooltip title={`${experiment.name}`}>
This will render `null` if the `name` is `null`. Let's use the empty string as a fallback.
```suggestion
              <Tooltip title={experiment.name ?? ''}>
```

2022-05-09 04:01 UTC, jessie-ross commented on src/components/experiments/single-view/ExperimentPageView.tsx
> +              <Tooltip title={`${experiment.name}`}>
Ah good find!

2022-05-09 11:58 UTC, razvanpapadopol approved these changes
🚀

2022-05-09 13:04 UTC, merged