Use Results as the default tab for non-staging experiments
Automattic/abacus pull request #766
Opened 2022-08-18 14:34 UTC by razvanpapadopol

Fixes https://github.com/Automattic/abacus/issues/742

When landing from the experiment directory or by using a `/experiments/{experimentId}` link, the default tab (`view`) should be:
 - 'Overview' for staging experiments
 - 'Results' for all other statuses
 
**Note:**
Before closing the original issue, we should extract thoughts from https://github.com/Automattic/abacus/issues/742 to new issues.
  
## How has this been tested?

- Automated tests that cover added/changed functionality
- Manual testing with production data (locally)
- Manual testing with mock data (locally or on Vercel)
- Additional manual testing instructions (please specify):

2022-08-19 18:47 UTC, aaronyan approved these changes
LGTM! Works on my local machine too as expected.

2022-08-19 18:49 UTC, aaronyan approved these changes
LGTM! Works on my local machine too as expected.

2022-08-22 06:59 UTC, jessie-ross requested changes

2022-08-22 06:59 UTC, jessie-ross commented on src/components/experiments/single-view/ExperimentPageView.tsx
> +  const view = viewFromPath || (!!experiment && (canEditInWizard ? ExperimentView.Overview : ExperimentView.Results))
Can we change this to redirect to the view if the view doesn't exist, I think that's a cleaner solution and will mean the URL will always reference the same page:
```
if (!view) {
    history.replace(`${location.pathname}/${(!!experiment && (canEditInWizard ? ExperimentView.Overview : ExperimentView.Results)}`)
}
```
Probably in a useEffect.

2022-08-23 17:02 UTC, razvanpapadopol commented on src/components/experiments/single-view/ExperimentPageView.tsx
> +  const view = viewFromPath || (!!experiment && (canEditInWizard ? ExperimentView.Overview : ExperimentView.Results))
Thanks for the suggestion, @jessie-ross ! Implemented in https://github.com/Automattic/abacus/pull/766/commits/a3abee5a9c85d4852f2fcf0a557910be667cd19e together with a bit of logic cleanup and it works really well 🙌🏼

2022-08-24 05:13 UTC, jessie-ross approved these changes
Thanks for adding the redirect in!

2022-08-24 09:18 UTC, merged