Experiment results: add impact credible intervals
Automattic/abacus pull request #772
Opened 2022-08-24 17:19 UTC by razvanpapadopol

### Summary of changes:
* Adds impact column to the Metric Assignments Table after the Absolute change column
* Adds an inline Select for impact interval in the table header for the new column
  * The interval defaults to "Year"
* Adds 'conversion_impact' and 'revenue_impact' types of metric formatting
  * `impactNumberFormatter` function transforms millions (eg: `2.51M`) and thousands (eg: `1.25M`)
  * Good to test with 20571-explat-experiment and `pipe_*` experiments
* Also, for the new column to fit in the table:
  * reduce width of the Metric name column of the Metric Assignments table and 
  * always display attribution window below the metric name.

### Demo:
* See how the left side of the interval is saying much more than the 'Absolute change' does
<img width="427" alt="Screen Shot 2022-08-24 at 19 21 47" src="https://user-images.githubusercontent.com/14192054/186480122-62765a6e-d4c2-4a4e-8a99-766c01674308.png">

* Another example with more context and a transformation for millions
<img width="654" alt="Screen Shot 2022-08-24 at 19 20 18" src="https://user-images.githubusercontent.com/14192054/186480134-29fbe741-4564-4e54-bb3d-75091848e098.png">

* In very rare cases (conversion rate values with 6+ digits), the table header might be displayed on 2 lines
<img width="1238" alt="Screen Shot 2022-08-24 at 19 19 25" src="https://user-images.githubusercontent.com/14192054/186480145-f2d2e7a4-0148-4e3b-8a86-bae1c1c9d113.png">

### To do:
- [ ] Discuss if we should show the impact column only after a minimum runtime or volume of analyzed participants
- [ ] Add a ready-to-share description phrase to the Summary section of metric details
- [ ] Test coverage

### Follow up:
- [ ] Update FG

## How has this been tested?

- Automated tests that cover added/changed functionality : WIP
- Manual testing with production data (locally)

2022-08-24 23:14 UTC, aaronyan reviewed
This is looking really great so far, @razvanpapadopol. Nice work and great attention to detail with the thousands (K) and millions (M) and the dropdown impact time period!

Being able to report absolute impact as a function of monthly conversions / USD is so cool. You're right, the 20571-explat-experiment is a great example!

> In very rare cases (conversion rate values with 6+ digits), the table header might be displayed on 2 lines

If everyone agrees, I am totally cool with replacing 'Absolute change' column with 'Impact'. I don't think we need both!

> Discuss if we should show the impact column only after a minimum runtime or volume of analyzed participants

I think it is okay to show the impact right away, since high uncertainty will be reflected as a wide interval. I'm curious to hear y'alls opinion!
> Add a ready-to-share description phrase to the Summary section of metric details

I like that a lot! I think we could simply replace the 'absolute change' values with 'absolute impact' values.

2022-08-25 06:41 UTC, jessie-ross commented
Nice work Razvan!! Can't wait for this to go out to experimenters!

> If everyone agrees, I am totally cool with replacing 'Absolute change' column with 'Impact'. I don't think we need both!

I think we should keep both, as impact makes some assumptions that absolute change doesn't make.
On that note I think we need to downgrade the certainty of Impact, I think we should rename it "Guessed Impact".

> I think it is okay to show the impact right away, since high uncertainty will be reflected as a wide interval. I'm curious to hear y'alls opinion!

👍 

> I like that a lot! I think we could simply replace the 'absolute change' values with 'absolute impact' values.

I think lift figures are still important for experimenters and marketing teams.

2022-08-25 06:44 UTC, jessie-ross commented on src/components/general/MetricValue.tsx
> +  revenue_impact: {
Revenue impact and revenue are the same unit: the count of dollars. 
We should join the `usdFormatter` and the `impactNumberFormatter` together.

2022-08-25 17:29 UTC, aaronyan commented
> I think we should keep both, as impact makes some assumptions that absolute change doesn't make.

I don't think I've seen anyone use 'absolute change' in their analysis, and I think showing both feels redundant. I'm cool with keeping it for now in this PR, and we can always iterate in the future.

> On that note I think we need to downgrade the certainty of Impact, I think we should rename it "Guessed Impact".

I love that! How about 'estimated impact'?

> > > Add a ready-to-share description phrase to the Summary section of metric details
> >
> > I like that a lot! I think we could simply replace the 'absolute change' values with 'absolute impact' values.
>
> I think lift figures are still important for experimenters and marketing teams.

@jessie-ross, are you thinking to add a lift sentence to summary?

<img width="1126" alt="Screen Shot 2022-08-25 at 10 21 20 AM" src="https://user-images.githubusercontent.com/4505888/186729806-785db32e-2957-4456-b695-3ac3587178fc.png">

I think @razvanpapadopol was hoping to add a sentence to the summary section of a metric details? I was thinking we could replace 'absolute change' with 'impact', so the sentence would read:

"The estimated monthly impact in ARPU of -71k to +12k USD is not statistically different from zero because the interval includes zero. Uncertainty is too high because the absolute change overlaps with the monthly minimum practical difference between -55k to +55k USD."

2022-08-26 07:42 UTC, jessie-ross commented
> are you thinking to add a lift sentence to summary?

Sorry I was confusing relative and absolute change here, I thinking we were replacing the lift with impact, instead of absolute change with impact.

I think absolute figures are very important, they are what Experimenters should be getting to know more than lift (which  they can't get to know as it changes depending on the absolute figures.)

2022-08-26 20:59 UTC, razvanpapadopol commented
> downgrade the certainty of Impact, I think we should rename it "Guessed Impact".

Yes, definitely! It's not about guaranteed or even projected impact but rather a synthetic extrapolation of the results.

> I don't think I've seen anyone use 'absolute change' in their analysis, and I think showing both feels redundant. I'm cool with keeping it for now in this PR, and we can always iterate in the future.

Yes, let's keep them for now as the UI is able to fit everything and we'll just keep an eye on how experimenters are using the values when sharing the following experiment results.

> I think absolute figures are very important, they are what Experimenters should be getting to know more than lift (which they can't get to know as it changes depending on the absolute figures.)

I agree we should try to keep the absolute diff visible as they are also connected to min diff and together are determining the analysis conclusion for a metric.

2022-08-29 11:16 UTC, razvanpapadopol commented on src/lib/analyses.ts
> +export enum ImpactInterval {
Done in https://github.com/Automattic/abacus/pull/772/commits/7640acd85eb5c47122bb0ce7bd67bdd2ec045fbb

2022-08-29 11:18 UTC, razvanpapadopol commented on src/components/general/MetricValue.tsx
> +    unit: '',
I can see it's a bit difficult to navigate the fine line between metric type and units. Then, the formatting is another layer 😁 Let's discuss more on this (and some other comments below) in https://github.com/Automattic/abacus/pull/774

2022-08-29 14:56 UTC, jessie-ross requested changes

2022-08-29 14:56 UTC, jessie-ross commented on src/lib/analyses.ts
> +export function getImpactMultiplier(
- This should be called `estimateTotalParticipantsInPeriod` (which is what it does) rather than introducing the new terminology of `impactMultiplier`.
- I think it should work in days to make it general purpose.
- Type should be `(analysis, experiment, periodInDays) => number`
- We would need to look at the variation allocation percentages.
- Needs function documentation.

2022-08-29 14:56 UTC, jessie-ross commented on src/components/experiments/single-view/results/ImpactIntervalSelector.tsx
> +export const ImpactIntervalInMonths: Record<ImpactInterval, number> = {
I don't like how these live here - it is tying the analysis code too hard to the UI, really this is just a time interval selector where we specify labels for certain intervals.

We should be able to pass in `(months, onSetMonths: (months: number) => void)` instead.

2022-08-29 14:56 UTC, jessie-ross commented on src/components/experiments/single-view/results/MetricAssignmentResults.tsx
> +    latestAnalysis.participantStats['total'],
I don't think this takes into account experiments with less than 100% allocation to variations.

2022-08-29 14:56 UTC, jessie-ross commented on src/components/experiments/single-view/results/ExperimentResults.tsx
> +            <ImpactIntervalSelector
I think the page is simpler with just one selector at the top level, rather than also selectors per metricAssignment.

I think it results in better UX:
- Users know what they are comparing across metrics.
- No way to get lost in what has been set where.

We can also inline the select and the analysis functions if that's the case.

2022-08-29 15:29 UTC, razvanpapadopol commented on src/components/experiments/single-view/results/MetricAssignmentResults.tsx
> +    latestAnalysis.participantStats['total'],
I thought that even if the allocation is, let's say 20%, that population is still representative of the entire targeted audience. If that's not correct, I still consider useful to use the `total` number of participants and maybe include in the [estimated impact disclaimer](https://github.com/Automattic/abacus/pull/772/files#diff-371c70a25deef9b4efcdb7ca1f7ac64bae51c82513c32e5cd392054f986b6c69R484-R485) something like `[...] conditions were unchanged for one {impactInterval}, across all participants`.

2022-08-29 21:01 UTC, aaronyan commented on src/components/experiments/single-view/results/MetricAssignmentResults.tsx
> +    latestAnalysis.participantStats['total'],
> we should be looking at our best guess of population rather than samples/representations of the population

I think it makes sense to have the estimates be based on the estimated total population (rather than the samples). It would be as as simple as dividing by total allocated percentage:`totalParticipants / totalAllocatedPercentage` where `totalAllocatedPercentage` can be between `0` and `1`.

If we feel strongly one way or another, we could make the population another toggle and put it next to the [top-level interval toggle](https://github.com/Automattic/abacus/pull/772#discussion_r957437210) (targeted, whole). If `totalAllocatedPercentage`, we could default to `whole` and disable the toggle.

2022-08-30 09:07 UTC, jessie-ross commented on src/components/experiments/single-view/results/MetricAssignmentResults.tsx
> +    latestAnalysis.participantStats['total'],
> If we feel strongly one way or another, we could make the population another toggle and put it next to the https://github.com/Automattic/abacus/pull/772#discussion_r957437210 (targeted, whole). If totalAllocatedPercentage, we could default to whole and disable the toggle.

Uhhh... I feel strongly that we shouldn't provide this as an option - more complexity for the code and UX.

2022-10-20 14:56 UTC, razvanpapadopol commented on src/components/general/MetricValue.tsx
> +  revenue_impact: {
Yes, the unit type (USD or cash) is the same but they require different formatting. 

In a [follow-up PR](https://github.com/Automattic/abacus/pull/774/files#diff-6e88ab8578a50fa634687bfa0a325b8cec511bd1f473b152e112f8787814ac6f), I propose handling the formatting explicitly because what we use now for `usdFormatter` is actually more generic than that and can be called `localizeNumberToFixedDecimals`, while for the impact values we'd likely use an abbreviation.

See also https://github.com/Automattic/abacus/pull/772#discussion_r957194197

2022-10-20 15:05 UTC, razvanpapadopol commented on src/components/general/MetricValue.tsx
> +  return metricValueFormatData[`${metricParameterType}${isDifference ? '_difference' : ''}${isImpact ? '_impact' : ''}`]
See my comments above. I think a new `formatter` prop on `MetricValue` [will remove the need](https://github.com/Automattic/abacus/pull/774/files#diff-7ec1a52a765aa5060aa0307214720f40ae0435b60abe68f3e1455b1fe64d3e3dL76-L85) for both `_difference` and `_impact` while enabling further extensibility (eg: importing a 3rd party formatting function as long as it's type `NumberToString`).

2022-10-20 15:07 UTC, razvanpapadopol commented on src/components/general/MetricValue.tsx
> +    postfix: '',
Added the postfix in https://github.com/Automattic/abacus/pull/772/commits/6ac08c5d15938d2f980accaea61ab15f69de8e74

2022-10-20 18:11 UTC, razvanpapadopol commented on src/lib/analyses.ts
> +export function getImpactMultiplier(
Thanks for the hints!

> We would need to look at the variation allocation percentages

This was addressed in https://github.com/Automattic/abacus/pull/772/commits/72c832a25ca562d931fb8b53f5ce13ea6fe9c14c as discussed in https://github.com/Automattic/abacus/pull/772#discussion_r957505000 and below.

Everything else was included in  https://github.com/Automattic/abacus/pull/772/commits/a7b40e790af88fd508d803a9ac502d5d30c9a83e

2022-10-20 18:14 UTC, razvanpapadopol commented on src/components/experiments/single-view/results/ImpactIntervalSelector.tsx
> +export const ImpactIntervalInMonths: Record<ImpactInterval, number> = {
Good point! Cleaned up the unnecessary type and map and started to pass `months: number` in https://github.com/Automattic/abacus/commit/a7b40e790af88fd508d803a9ac502d5d30c9a83e

2022-10-20 19:38 UTC, razvanpapadopol commented on src/components/experiments/single-view/results/MetricAssignmentResults.tsx
> +                </Typography>
This should cover aproximately what was summarised in pbmo2S-1Cf-p2#comment-2550 and the other convos we had.
* the relative change, together with the estimated impact in the same sentence
* a hint on how we calculate the estimated impact by including the experiment runtime 
* visible disclaimer that this is not a statistical forecast

We may also include here a link to a detailed explanation in FG

2022-10-20 19:41 UTC, razvanpapadopol commented on src/components/experiments/single-view/results/MetricAssignmentResults.tsx
> +                    metricParameterType={MetricParameterType.Conversion}
We shouldn't need to pass the `Conversion` metric type to display relative change. This applies also to "Estimated impact" column in `ExperimentResults` component and should be fixed with the refactor in https://github.com/Automattic/abacus/pull/774

2022-10-20 19:47 UTC, razvanpapadopol commented on src/components/experiments/single-view/results/ExperimentResults.tsx
> +            <ImpactIntervalSelector
As it is right now, the selector is displayed only at top level, in the header of Metric Assignment Results table. Selecting the interval there applies to every metric and also to every Metric Detail text.

2022-10-20 23:47 UTC, razvanpapadopol commented
Hey @aaronyan and @jessie-ross! I think this is now ready for another round of reviews. I've updated also the PR description and Demo and here's a quick summary of changes:
* Merged the impact interval and "Relative change (lift)" into an "Estimated Impact" column as described in [#780](https://github.com/Automattic/abacus/issues/780), with vertical centering. Other style changes are going into a separate PR for easier reviewing.
* Updated estimated impact interval tooltip content and the [sentence in the Metric Details - Summary](https://github.com/Automattic/abacus/pull/772#discussion_r1001041327).
* [Total allocated percentage](https://github.com/Automattic/abacus/pull/772#discussion_r957434057) is now taken into consideration.

2022-10-21 13:08 UTC, jessie-ross commented on src/components/experiments/single-view/results/MetricAssignmentResults.tsx
> +    latestAnalysis.participantStats['total'],
As an aside, this might actually be a different calculation to the impact from pipe, as they will want just their treatment sample to show the incremental money made.

2022-10-21 13:30 UTC, jessie-ross commented on src/components/experiments/single-view/results/MetricAssignmentResults.tsx
> +                </Typography>
I'm fine with this for this PR, but I think we should include the number of participants over the time period as it is an important factor of the calculation.

2022-10-21 15:34 UTC, jessie-ross approved these changes
Woo! Thanks for all your work on this!

It's looking good!

2022-10-21 22:49 UTC, aaronyan approved these changes
Yay, amazing job @razvanpapadopol! Tests well and looks great so far. I'm excited to get this in the hands of experimenters. Thanks for iterating and being so thoughtful in the implementation.

I think we can improve the decimal rounding on the estimated impact in a future PR. Some quick thoughts for now:
- No postfix, round to whole number. 451 stays the same
- Has a postfix (K, M) round to a single decimal. 4.51K -> 4.5K.

Relative percentages can also probably use some rounding love: 
- Below 5% round to two decimals. 3.94% stays the same
- Below 30% round to one decimal. 20.24% -> 20.2%
- Otherwise round to whole percents. 45.12% -> 45%

2022-10-24 21:58 UTC, merged

2022-10-29 07:35 UTC, razvanpapadopol commented on src/components/experiments/single-view/results/MetricAssignmentResults.tsx
> +                    metricParameterType={MetricParameterType.Conversion}
Done in https://github.com/Automattic/abacus/pull/774/files#diff-371c70a25deef9b4efcdb7ca1f7ac64bae51c82513c32e5cd392054f986b6c69L527