Add Min Diff Calculator to an existing experiment
Automattic/abacus pull request #782
Opened 2022-09-22 20:57 UTC by razvanpapadopol

## How has this been tested?

- Automated tests that cover added/changed functionality
- Manual testing with production data (locally)
- Manual testing with mock data (locally or on Vercel)
- Additional manual testing instructions (please specify):

2022-09-30 14:15 UTC, jessie-ross requested changes
Looking good, main change requested is moving the code within the `<Formik>` closure, I think that will simplify the code and make it simple to extract the form into its own component (something we should probably do as well.)

2022-09-30 14:15 UTC, jessie-ross commented on src/components/experiments/single-view/overview/MetricAssignmentsPanel.tsx
> +    newMinDiff && formikProps.setFieldValue('metricAssignment.minDifference', newMinDiff / 100)
It is a bit disappointing that the number coming out of the calculator needs to be divided by 100, ideally all the min diff values should be the same and we only change them for presentation.

2022-09-30 14:15 UTC, jessie-ross commented on src/components/experiments/single-view/overview/MetricAssignmentsPanel.tsx
> +
I think we should move the above new code to around line 275, within the `(formikProps) =>` function. 

That will simplify some things:
- We won't need to pass in/type formikProps
- We don't need a function to determine the parameter type, we can just us `const parameterType = `
- It keeps the add-metric functionality all in one place.

2022-09-30 14:15 UTC, jessie-ross commented on src/components/experiments/single-view/overview/MetricAssignmentsPanel.tsx
> +                        isConversion: getParameterType(formikProps) === MetricParameterType.Conversion,
I think the calculator should take a `MetricParameterType` rather than `isConversion`, we'll need it when we add new metric types like for pipe.

2022-10-07 17:53 UTC, razvanpapadopol commented on src/components/experiments/single-view/overview/MetricAssignmentsPanel.tsx
> +    newMinDiff && formikProps.setFieldValue('metricAssignment.minDifference', newMinDiff / 100)
I agree this needs to be fixed in the calculator itself and maybe also explore if it has something to do with MetricValue component. For now, I've added this point to https://github.com/Automattic/abacus/issues/756

2022-10-07 18:04 UTC, razvanpapadopol commented on src/components/experiments/single-view/overview/MetricAssignmentsPanel.tsx
> +
Done the simplification in https://github.com/Automattic/abacus/pull/782/commits/cf615e896ac712597692dd2dd5b9b706a55e13d7 and then the full extraction of `MetricAssignmentForm` component in https://github.com/Automattic/abacus/pull/782/commits/de93c165c52b303150e0491b362ee4b5b994d08c

2022-10-11 17:43 UTC, jessie-ross reviewed
I haven't gotten round to taking a good look at this yet, left some very small comments, I'll check back tomorrow.

2022-10-11 17:43 UTC, jessie-ross commented on src/components/experiments/single-view/overview/MetricAssignmentsPanel.tsx
> +
Thanks for going ahead and extracting the component!

2022-10-12 14:03 UTC, jessie-ross approved these changes
LGTM!

2022-10-12 20:39 UTC, razvanpapadopol commented on src/components/experiments/single-view/overview/MetricAssignmentsPanel.tsx
> +                        isConversion: getParameterType(formikProps) === MetricParameterType.Conversion,
Good point! I've changed the prop in https://github.com/Automattic/abacus/pull/782/commits/8d066f5a5e29202ac63843a645ae4ca2c4120bfe and, for now, the `isConversion` logic happens within the calculator. We can further improve it when needed.

2022-10-13 00:05 UTC, merged