Experiment Results: add colors to CI diagrams
Automattic/abacus pull request #787
Opened 2022-10-07 23:14 UTC by razvanpapadopol

Fixes https://github.com/Automattic/abacus/issues/778

#### Summary of changes
* Use green for results where we have enough data: `{variant} winning`, `no difference`
* Use yellow for cases where we need more data*: `inconclusive`, `{variant} ahead`, `{variant} barely ahead`
* Abacus custom `theme.palette` includes now these two colors

_*or other conditions must be met before we make a deployment recommendation_

#### Demo
<img width="600" alt="Screen Shot 2022-10-08 at 02 00 40" src="https://user-images.githubusercontent.com/14192054/194673894-58d3bcd1-2533-4ee7-81ee-597384196c9d.png">

## How has this been tested?

- Automated tests that cover added/changed functionality
- Manual testing with production data (locally)

2022-10-11 17:38 UTC, jessie-ross requested changes

2022-10-11 17:38 UTC, jessie-ross commented on src/components/experiments/single-view/results/CredibleIntervalVisualization.tsx
> +  const isEnoughData =
Shouldn't we be using [`isDataStrongEnough`](https://github.com/Automattic/abacus/blob/829fc876139645d941c3b08c2b859ca49e31a948/src/lib/recommendations.ts#L161-L202) for this logic?  

There are a few ways to do it such as  changing the input of this component to match the function call, or wrapping this in another component that provides a boolean of `isDataStrongEnough` for this component, or preferably for me, providing [the recommendation data](https://github.com/Automattic/abacus/blob/829fc876139645d941c3b08c2b859ca49e31a948/src/lib/recommendations.ts#L131) to this function.

2022-10-11 17:52 UTC, razvanpapadopol commented on src/components/experiments/single-view/results/CredibleIntervalVisualization.tsx
> +  const isEnoughData =
Oh, no. They are different as this one here is only "reading" the CI interval and min diff for a metric, disregarding the platform, runtime, etc. I think I should rename one or the other. `isDataStrongEnough` may as well be called `isDataStrongEnoughForDeploymentRecommendation` 😬 

> providing [the recommendation data](https://github.com/Automattic/abacus/blob/829fc876139645d941c3b08c2b859ca49e31a948/src/lib/recommendations.ts#L131) to this function.

This may work as it gives us access to `Decision` which can be used to map to colors exactly how we want:
> Use green for results where we have enough data: {variant} winning, no difference
> Use yellow for cases where we need more data*: inconclusive, {variant} ahead, {variant} barely ahead

2022-10-11 18:00 UTC, aaronyan commented on src/components/experiments/single-view/results/CredibleIntervalVisualization.tsx
> +  const isEnoughData =
I think we'll want the colors to use the same logic as adding a recommendation. If a metric has enough data for a recommendation, then we color the CI green. Otherwise, yellow.

2022-10-13 15:17 UTC, razvanpapadopol commented on src/components/experiments/single-view/results/CredibleIntervalVisualization.tsx
> +  const isEnoughData =
I see your point to have consistent logic to determine if a recommendation is based on strong data or not. I've pushed the changes and this is an example (using 20806-explat-experiment) where a previously yellow interval is now green:

<img width="690" alt="Screen Shot 2022-10-13 at 18 01 49" src="https://user-images.githubusercontent.com/14192054/195635436-38e3876f-5a94-483e-a93c-47d6b40bc59c.png">

If decision is one of `[VariantBarelyAhead, VariantAhead]`, should we display some explanation, maybe linking to a FG section such as PCYsg-Fqg-p2#reasons-for-not-enough-certainty ?

2022-10-13 23:10 UTC, aaronyan commented on src/components/experiments/single-view/results/CredibleIntervalVisualization.tsx
> +  const isEnoughData =
I love the idea of adding an explanation and linking the FG section!

2022-10-21 09:40 UTC, jessie-ross approved these changes
LGTM

2022-10-21 09:40 UTC, jessie-ross commented on src/components/experiments/single-view/results/CredibleIntervalVisualization.tsx
> +  const hasEnoughData = recommendation.strongEnoughData
Nit: This variable is unnecessary

2022-10-21 10:38 UTC, razvanpapadopol commented on src/components/experiments/single-view/results/CredibleIntervalVisualization.tsx
> +  const isEnoughData =
Great! I've opened the follow-up issue https://github.com/Automattic/abacus/issues/791 so we'll handle this extra bit in a separate PR. I'm releasing now the colored diagrams as they are already very informative by themselves 🚀

2022-10-21 10:39 UTC, merged