Wizard: add tags for filtering metrics
Automattic/abacus pull request #855
Opened 2023-04-03 23:48 UTC by razvanpapadopol

Fixes https://github.com/Automattic/experimentation-platform/issues/869

Renders tags as clickable Chip components to enable filtering in the Metrics step of the experiment wizard.
* Show selected (primary color) state for the active tag.
* Render loading state while fetching all tags.
* Use an "All" Chip as default state and to reset filtering.
* Only one tag can be applied at a time.
* Available only in debug mode.

## How has this been tested?

- Automated tests that cover added/changed functionality
- Manual testing with production data (locally)
- Manual testing with mock data (locally or on Vercel)
- Additional manual testing instructions (please specify):
  * Apply diff D104318-code and sandbox the wpcom API
  * Open the Metrics step of the Experiment Wizard and filter by metric tag
     * When "All" Chip tag is selected, all metrics should be displayed
     * The "assigned" metrics should remain regardless of the selected tag

2023-04-04 14:25 UTC, jessie-ross requested changes
Thanks for these PRs!

Hmm, I think we should be using the multi-chip search selector for tags that we use for targeting:
<img width="1067" alt="Screenshot 2023-04-04 at 10 22 29 pm" src="https://user-images.githubusercontent.com/971886/229823287-3493013a-bf1f-4a12-9c63-aac82e1e7d33.png">

See also my comment in the PI for overall thoughts on the UX:
https://github.com/Automattic/experimentation-platform/issues/864#issuecomment-1496050924

It might make things simpler if we had a top level selector in the header.

2023-04-04 14:25 UTC, jessie-ross commented on src/components/explat/experiments/wizard/Metrics.tsx
> +            // TODO: Try to include the tag.metricIds already available on backend in the tags API response.
I think this would be an unnecessary optimisation.

2023-04-04 14:25 UTC, jessie-ross commented on src/components/explat/experiments/wizard/Metrics.tsx
> +  const [selectedTagOption, setSelectedTagOption] = useState<TagFull | null>(null)
We should go with an array and allow multiple tags to be selected.

2023-04-04 20:27 UTC, razvanpapadopol commented on src/components/explat/experiments/wizard/Metrics.tsx
> +            // TODO: Try to include the tag.metricIds already available on backend in the tags API response.
Yeah, I guess we'll need a better case for including that list of ids 😬

2023-04-04 20:47 UTC, razvanpapadopol commented on src/components/explat/experiments/wizard/Metrics.tsx
> +  const [selectedTagOption, setSelectedTagOption] = useState<TagFull | null>(null)
I've also considered the multi-tag select but with this straight-forward solution (clickable chips with no search) I don't think it's very useful and it introduces a bit of an UX puzzle: "do we have an AND or an OR relation between selected tags?". I guess it would be "OR" and a likely use case could be "I'm adding a cross-division experiment and want to search for existing "purchase_*" metrics, right?

2023-04-04 20:57 UTC, razvanpapadopol commented
Thanks for checking these out, @jessie-ross !! 

> Hmm, I think we should be using the multi-chip search selector for tags that we use for targeting

After exploring a solution using the search selector in https://github.com/Automattic/abacus/pull/855 I've started to enjoy the simplicity of this one. If we manage to have a limited number or curated tags it's perfect for wizard. To filter the tags if they are too many, I guess we can use the tag (or its namespace) with the selected `platform`.

> It might make things simpler if we had a top level selector in the header.

I'm note sure if a top level selector will achieve this level of simplicity and it may cause some confusion for new users. Eg: I've set it to filter metrics directory for some division and then when I create an experiment I don't have a local cue that a filter has been applied. However, I like the idea of persisting last user selection locally ❤️

2023-04-05 02:35 UTC, aaronyan commented
I've commented on a proposed unified design [here](https://github.com/Automattic/experimentation-platform/issues/871#issuecomment-1496838448)!

2023-04-25 20:59 UTC, razvanpapadopol commented
Closing this in favour of https://github.com/Automattic/abacus/pull/854 based on all the discussions in https://github.com/Automattic/experimentation-platform/issues/871

2023-04-25 20:59 UTC, closed without merging